/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 *
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with
 * the terms contained in the written license agreement between you and ArcCore,
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as
 * published by the Free Software Foundation and appearing in the file
 * LICENSE.GPL included in the packaging of this file or here
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

#ifndef _RH850_PORTDEFS_H
#define _RH850_PORTDEFS_H

#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ADC PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ALT_7 PORT_FUNC7  SET_PIPC
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_SPI PORT_FUNC8  CLEAR_PIPC
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_MEM PORT_FUNC9  CLEAR_PIPC

#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_LIN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ADC PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ADC0 PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ALT_7 PORT_FUNC7  SET_PIPC
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_SPI PORT_FUNC8  CLEAR_PIPC
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ETH PORT_FUNC10  CLEAR_PIPC

#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_LIN PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ADC PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ALT_7 PORT_FUNC7  SET_PIPC
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_SPI PORT_FUNC8  CLEAR_PIPC
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_SPI0 PORT_FUNC9  CLEAR_PIPC
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ETH PORT_FUNC10  CLEAR_PIPC

#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_SPI PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_SPI0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_LIN PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_MEM PORT_FUNC9  CLEAR_PIPC

#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_SPI PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_SPI0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_ADC PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_LIN PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_MEM PORT_FUNC9  CLEAR_PIPC

#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_SPI PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_MEM PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_ETH PORT_FUNC8  CLEAR_PIPC

#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_SPI PORT_FUNC0  SET_PIPC
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_SPI0 PORT_FUNC1  SET_PIPC
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_LIN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_MEM PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_ETH PORT_FUNC9  CLEAR_PIPC

#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_SPI PORT_FUNC0  SET_PIPC
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_MEM PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_ETH PORT_FUNC8  CLEAR_PIPC

#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_SPI PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_MEM PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_ETH PORT_FUNC8  CLEAR_PIPC

#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_MEM PORT_FUNC6  CLEAR_PIPC

#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_MEM PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_ETH PORT_FUNC8  CLEAR_PIPC
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_ETH0 PORT_FUNC10  CLEAR_PIPC
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_SPI PORT_FUNC12  CLEAR_PIPC
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_SPI0 PORT_FUNC13  CLEAR_PIPC

#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_MEM PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_ETH PORT_FUNC8  CLEAR_PIPC
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_ETH0 PORT_FUNC10  CLEAR_PIPC
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_SPI PORT_FUNC12  CLEAR_PIPC

#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_ETH PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_SPI PORT_FUNC4  CLEAR_PIPC

#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_SPI PORT_FUNC4  SET_PIPC
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_ETH PORT_FUNC6  SET_PIPC

#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_ETH PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_SPI PORT_FUNC4  SET_PIPC
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_SPI0 PORT_FUNC5  SET_PIPC

#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_LIN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_CAN PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_SPI PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_ALT_7 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_CAN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_LIN PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_SPI PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_ALT_7 PORT_FUNC7  CLEAR_PIPC

#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_CAN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_LIN PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_SPI PORT_FUNC6  SET_PIPC
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_ALT_8 PORT_FUNC8  CLEAR_PIPC
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_ALT_9 PORT_FUNC9  CLEAR_PIPC

#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_LIN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_CAN PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_SPI PORT_FUNC6  SET_PIPC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_SPI0 PORT_FUNC7  SET_PIPC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_ALT_8 PORT_FUNC8  CLEAR_PIPC

#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_CAN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_SPI PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_ALT_5 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_ALT_6 PORT_FUNC6  CLEAR_PIPC

#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_CAN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_ALT_3 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_SPI PORT_FUNC4  SET_PIPC
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_SPI0 PORT_FUNC5  SET_PIPC

#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_ALT_3 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_SPI PORT_FUNC4  SET_PIPC
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_PWM PORT_FUNC9  CLEAR_PIPC

#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_SPI PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_LIN PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_PWM PORT_FUNC7  CLEAR_PIPC

#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_SPI PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_LIN PORT_FUNC7  CLEAR_PIPC

#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_SPI PORT_FUNC6  SET_PIPC
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_SPI0 PORT_FUNC7  SET_PIPC
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_CAN PORT_FUNC8  CLEAR_PIPC

#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_SPI PORT_FUNC6  SET_PIPC
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_CAN PORT_FUNC9  CLEAR_PIPC

#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC

#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_CAN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_CAN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_CAN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_CAN PORT_FUNC1  CLEAR_PIPC

#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_ADC PORT_FUNC1  CLEAR_PIPC

#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_SPI PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_SPI PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_SPI PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_ALT_1 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_ICU PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_ICU0 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_ALT_1 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_ICU PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_ICU0 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_ICU PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_ICU0 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_ICU PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_ICU0 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_CAN PORT_FUNC3  CLEAR_PIPC

#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_CAN PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_ADC PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC

#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC

#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_LIN PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_CAN PORT_FUNC9  CLEAR_PIPC

#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_LIN PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_CAN PORT_FUNC8  CLEAR_PIPC

#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_SPI PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_SPI0 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_CAN PORT_FUNC9  CLEAR_PIPC

#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_ALT_3 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_SPI PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_SPI0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_CAN PORT_FUNC8  CLEAR_PIPC

#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_ADC PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_ADC PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC

#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_ADC PORT_FUNC3  CLEAR_PIPC

#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_ADC PORT_FUNC3  CLEAR_PIPC

#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC

#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC

#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_SPI PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_ICU PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_SPI PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_SPI PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_SPI PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_SPI PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_ALT_5 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ICU PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ICU0 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ADC PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_SPI PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ALT_6 PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ADC0 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ICU PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ICU0 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_SPI PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_SPI PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_SPI PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_CAN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_LIN PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_SPI PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_SPI0 PORT_FUNC7  CLEAR_PIPC

#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_CAN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_LIN PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_SPI PORT_FUNC6  SET_PIPC

#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_CAN PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_SPI PORT_FUNC6  SET_PIPC
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_SPI0 PORT_FUNC7  SET_PIPC

#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_CAN PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_SPI PORT_FUNC6  CLEAR_PIPC

#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC

#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_SPI PORT_FUNC6  CLEAR_PIPC

#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_SPI PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_SPI0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_LIN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_ETH PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_ETH0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_ETH PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_ETH0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_ETH PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_ETH PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_ETH PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_ETH0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_ETH PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_ETH PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_ADC SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_SPI PORT_FUNC2  SET_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_SPI0 PORT_FUNC3  SET_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_ADC PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_CAN PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_SPI PORT_FUNC2  SET_PIPC
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_CAN PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_SPI PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_FLEXRAY PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_MEM PORT_FUNC6  SET_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_LIN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_SPI PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_SPI0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_FLEXRAY PORT_FUNC10  CLEAR_PIPC

#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_FLEXRAY PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_LIN PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_SPI PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_LIN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_FLEXRAY PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_SPI PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_FLEXRAY PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_LIN PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_SPI PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_SPI PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_LIN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_FLEXRAY PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_ADC PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_PWM PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_FLEXRAY PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_LIN PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_SPI PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_SPI PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_FLEXRAY PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_LIN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_SPI0 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_SPI PORT_FUNC0  SET_PIPC
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_SPI0 PORT_FUNC1  SET_PIPC
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_LIN PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_SPI PORT_FUNC0  SET_PIPC
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_CAN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_MEM PORT_FUNC6  SET_PIPC

#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_SPI PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_CAN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_MEM PORT_FUNC6  SET_PIPC

#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_CAN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_SPI PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_CAN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_ADC PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_SPI PORT_FUNC4  SET_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_SPI0 PORT_FUNC5  SET_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_ALT_0 PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_SPI PORT_FUNC4  SET_PIPC
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_ICU PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_ICU0 PORT_FUNC7  CLEAR_PIPC
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_MEM PORT_FUNC8  SET_PIPC

#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_CAN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_MEM PORT_FUNC7  CLEAR_PIPC

#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_CAN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_MEM PORT_FUNC7  CLEAR_PIPC

#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_LIN PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_SPI PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_MEM PORT_FUNC7  CLEAR_PIPC

#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_LIN PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_PWM PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_ICU PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_ICU0 PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_MEM PORT_FUNC7  CLEAR_PIPC

#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_CAN PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_ALT_3 PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_ALT_7 PORT_FUNC7  SET_PIPC
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_SPI PORT_FUNC8  CLEAR_PIPC
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_MEM PORT_FUNC9  CLEAR_PIPC
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_ETH PORT_FUNC10  CLEAR_PIPC

#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_CAN PORT_FUNC3  CLEAR_PIPC
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_ALT_7 PORT_FUNC7  SET_PIPC
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_SPI PORT_FUNC8  SET_PIPC
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_ETH PORT_FUNC10  CLEAR_PIPC
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_ETH0 PORT_FUNC12  CLEAR_PIPC
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC

#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_DIO_GPT PORT_MODE
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_DIO_WDG PORT_MODE
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ICU PORT_FUNC0  CLEAR_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ICU0 PORT_FUNC1  CLEAR_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ALT_2 PORT_FUNC2  CLEAR_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ALT_4 PORT_FUNC4  CLEAR_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_PWM PORT_FUNC5  CLEAR_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ADC PORT_FUNC6  CLEAR_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ALT_7 PORT_FUNC7  SET_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_SPI PORT_FUNC8  SET_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_SPI0 PORT_FUNC9  SET_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ETH PORT_FUNC10  CLEAR_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ETH0 PORT_FUNC12  CLEAR_PIPC
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ALT_14 SPECIAL_FUNC  CLEAR_PIPC


#endif
