#ifndef _RH850F1LPORTS_H
#define _RH850F1LPORTS_H


/* Pin:1 Name:AP0_0 */
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ADCA0_ADCA0I0_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:2 Name:AP0_1 */
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ADCA0_ADCA0I1_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:3 Name:AP0_2 */
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ADCA0_ADCA0I2_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:4 Name:AP0_3 */
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_ADCA0_ADCA0I3_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:5 Name:AP0_4 */
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_ADCA0_ADCA0I4_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:6 Name:AP0_5 */
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_ADCA0_ADCA0I5_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:7 Name:AP0_6 */
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_ADCA0_ADCA0I6_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:8 Name:AP0_7 */
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_ADCA0_ADCA0I7_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:9 Name:AP0_8 */
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_ADCA0_ADCA0I8_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:10 Name:AP0_9 */
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_ADCA0_ADCA0I9_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:11 Name:AP0_10 */
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_ADCA0_ADCA0I10_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:12 Name:AP0_11 */
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_ADCA0_ADCA0I11_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:13 Name:AP0_12 */
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_ADCA0_ADCA0I12_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:14 Name:AP0_13 */
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_ADCA0_ADCA0I13_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:15 Name:AP0_14 */
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_ADCA0_ADCA0I14_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:16 Name:AP0_15 */
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_ADCA0_ADCA0I15_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:17 Name:AP1_0 */
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_ADCA1_ADCA1I0_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:18 Name:AP1_1 */
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_ADCA1_ADCA1I1_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:19 Name:AP1_2 */
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_ADCA1_ADCA1I2_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:20 Name:AP1_3 */
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_ADCA1_ADCA1I3_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:21 Name:AP1_4 */
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_ADCA1_ADCA1I4_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:22 Name:AP1_5 */
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_ADCA1_ADCA1I5_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:23 Name:AP1_6 */
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_ADCA1_ADCA1I6_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:24 Name:AP1_7 */
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_ADCA1_ADCA1I7_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:25 Name:AP1_8 */
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_ADCA1_ADCA1I8_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:26 Name:AP1_9 */
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_ADCA1_ADCA1I9_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:27 Name:AP1_10 */
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_ADCA1_ADCA1I10_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:28 Name:AP1_11 */
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_ADCA1_ADCA1I11_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:29 Name:AP1_12 */
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_ADCA1_ADCA1I12_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:30 Name:AP1_13 */
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_ADCA1_ADCA1I13_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:31 Name:AP1_14 */
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_ADCA1_ADCA1I14_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:32 Name:AP1_15 */
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_ADCA1_ADCA1I15_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:33 Name:JP0_0 */
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_INTP_INTP0_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DEBUG_DCUTDI_LPDI_LPDIO_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:34 Name:JP0_1 */
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_INTP_INTP1_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_TAUJ0_TAUJ0I0_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_TAUJ0_TAUJ0O0_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DEBUG_DCUTDO_LPDO_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:35 Name:JP0_2 */
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_INTP_INTP2_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_TAUJ0_TAUJ0I1_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_TAUJ0_TAUJ0O1_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_DEBUG_DCUTCK_LPDCLK_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:36 Name:JP0_3 */
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_INTP_INTP3_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_CSCXFOUT_CSCXFOUT_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_TAUJ0_TAUJ0I2_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_TAUJ0_TAUJ0O2_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC

/* Pin:37 Name:JP0_4 (*18) */
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:38 Name:JP0_5 */
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_INTP_NMI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_RTCA_RTCA0OUT_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_TAUJ0_TAUJ0I3_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_TAUJ0_TAUJ0O3_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DEBUG__DCURDY_LPDCLKOUT_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:39 Name:JP0_6 */
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:40 Name:P0_0 */
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_TAUD0_TAUD0I2_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_TAUD0_TAUD0O2_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_RLIN2_RLIN20RX_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_CAN0_CAN0TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_PWGA_PWGA10O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_CSIH0__CSIH0SSI_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_LPS_DPO_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:41 Name:P0_1 */
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_TAUD0_TAUD0I4_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_TAUD0_TAUD0O4_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_CAN0_CAN0RX_INTP0_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_RLIN2_RLIN20TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_INTP_INTP0_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_PWGA_PWGA11O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_CSIH0_CSIH0SI_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_LPS_APO_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:42 Name:P0_2 */
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_TAUD0_TAUD0I6_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_TAUD0_TAUD0O6_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_CAN1_CAN1RX_INTP1_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_RLIN3_RLIN30TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_PWGA_PWGA12O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_CSIH0_CSIH0SC_PORT_PIN_IN PORT_FUNC6 SET_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_CSIH0_CSIH0SC_PORT_PIN_OUT PORT_FUNC7 SET_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_INTP_INTP1_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_LPS_DPO_PORT_PIN_OUT PORT_FUNC9 CLEAR_PIPC

/* Pin:43 Name:P0_3 */
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_TAUD0_TAUD0I8_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_TAUD0_TAUD0O8_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_RLIN3_RLIN30RX_INTP10_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_CAN1_CAN1TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_LPS_DPIN1_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_PWGA_PWGA13O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_CSIH0_CSIH0SO_PORT_PIN_OUT PORT_FUNC7 SET_PIPC
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_INTP_INTP10_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC

/* Pin:44 Name:P0_4 */
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_RLIN3_RLIN31RX_INTP11_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_CAN2_CAN2TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_INTP_INTP11_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_PWGA_PWGA10O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_CSIH1_CSIH1SI_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_LPS_SELDP0_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_LPS_DPIN8_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC

/* Pin:45 Name:P0_5 */
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_CAN2_CAN2RX_INTP2_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_RLIN3_RLIN31TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_LPS_DPIN9_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_LPS_SELDP1_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_CSIH1_CSIH1SO_PORT_PIN_OUT PORT_FUNC5 SET_PIPC

/* Pin:46 Name:P0_6 */
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_INTP_INTP2_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_LPS_DPIN10_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_LPS_SELDP2_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_CSIH1_CSIH1SC_PORT_PIN_IN PORT_FUNC4 SET_PIPC
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_CSIH1_CSIH1SC_PORT_PIN_OUT PORT_FUNC5 SET_PIPC
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_PWGA_PWGA35O_PORT_PIN_OUT PORT_FUNC9 CLEAR_PIPC

/* Pin:47 Name:P0_7 */
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_RLIN2_RLIN21RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_LPS_DPIN5_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_CSCXFOUT_CSCXFOUT_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_CSIH1_CSIH1RYI_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_CSIH1_CSIH1RYO_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_TAUB0_TAUB0I0_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_TAUB0_TAUB0O0_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_CAN3_CAN3RX_INTP3_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC

/* Pin:48 Name:P0_8 */
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_RLIN2_RLIN21TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_LPS_DPIN6_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_CSIH0_CSIH0CSS6_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_CSIH1__CSIH1SSI_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_TAUB0_TAUB0I2_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_TAUB0_TAUB0O2_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_CAN3_CAN3TX_PORT_PIN_OUT PORT_FUNC9 CLEAR_PIPC

/* Pin:49 Name:P0_9 */
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_INTP_INTP12_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_CSIH1_CSIH1CSS0_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_LPS_DPIN7_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_RLIN2_RLIN22RX_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_TAUB0_TAUB0I4_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_TAUB0_TAUB0O4_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_CAN4_CAN4RX_INTP4_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC

/* Pin:50 Name:P0_10 */
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_INTP_INTP3_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_CSIH1_CSIH1CSS1_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_LPS_DPIN11_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_RLIN2_RLIN22TX_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_TAUB0_TAUB0I6_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_TAUB0_TAUB0O6_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_CAN4_CAN4TX_PORT_PIN_OUT PORT_FUNC9 CLEAR_PIPC

/* Pin:51 Name:P0_11 */
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_RIIC0_RIIC0SDA_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_RIIC0_RIIC0SDA_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_LPS_DPIN12_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_CSIH1_CSIH1CSS2_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_TAUB0_TAUB0I8_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_TAUB0_TAUB0O8_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_RLIN2_RLIN26RX_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_PWGA_PWGA34O_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:52 Name:P0_12 */
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_RIIC0_RIIC0SCL_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_RIIC0_RIIC0SCL_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_LPS_DPIN13_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_PWGA_PWGA45O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_TAUB0_TAUB0I10_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_TAUB0_TAUB0O10_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_CSIG0_CSIG0SI_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_RLIN2_RLIN26TX_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:53 Name:P0_13 */
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_RLIN3_RLIN32RX_INTP12_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_INTP_INTP12_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_PWGA_PWGA46O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_TAUB0_TAUB0I12_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_TAUB0_TAUB0O12_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_CSIG0_CSIG0SO_PORT_PIN_OUT PORT_FUNC7 SET_PIPC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_CAN5_CAN5RX_INTP5_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC

/* Pin:54 Name:P0_14 */
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_RLIN3_RLIN32TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_PWGA_PWGA47O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_TAUB0_TAUB0I14_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_TAUB0_TAUB0O14_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_CSIG0_CSIG0SC_PORT_PIN_IN PORT_FUNC6 SET_PIPC
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_CSIG0_CSIG0SC_PORT_PIN_OUT PORT_FUNC7 SET_PIPC
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_CAN5_CAN5TX_PORT_PIN_OUT PORT_FUNC9 CLEAR_PIPC

/* Pin:55 Name:P1_0 */
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_RLIN3_RLIN33RX_INTP13_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_INTP_INTP13_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:56 Name:P1_1 */
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_RLIN3_RLIN33TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:57 Name:P1_2 */
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_CAN3_CAN3RX_INTP3_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_INTP_INTP3_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:58 Name:P1_3 */
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_CAN3_CAN3TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_LPS_DPIN23_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:59 Name:P1_4 */
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_RLIN3_RLIN35RX_INTP15_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_INTP_INTP15_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:60 Name:P1_5 */
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_ADCA1_ADCA1TRG0_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_RLIN3_RLIN35TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_LPS_DPIN17_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:61 Name:P1_6 */
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_RLIN2_RLIN25RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_LPS_DPIN18_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:62 Name:P1_7 */
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_ADCA1_ADCA1TRG1_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_RLIN2_RLIN25TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_LPS_DPIN19_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:63 Name:P1_8 */
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_RLIN3_RLIN34RX_INTP14_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_INTP_INTP14_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:64 Name:P1_9 */
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_RLIN3_RLIN34TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_LPS_DPIN20_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:65 Name:P1_10 */
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_RLIN2_RLIN24RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_LPS_DPIN21_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:66 Name:P1_11 */
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_ADCA1_ADCA1TRG2_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_RLIN2_RLIN24TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_LPS_DPIN22_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:67 Name:P1_12 */
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_CAN4_CAN4RX_INTP4_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_INTP_INTP4_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:68 Name:P1_13 */
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_CAN4_CAN4TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:69 Name:P1_14 */
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_RLIN2_RLIN23RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_CANP_INTP9_CAN7RX_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:70 Name:P1_15 */
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_RLIN2_RLIN23TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_CAN7_CAN7TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC

/* Pin:71 Name:P2_0 */
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_RLIN2_RLIN27RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_CANP_INTP6_CAN6RX_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:72 Name:P2_1 */
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_RLIN2_RLIN27TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_CAN6_CAN6TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC

/* Pin:73 Name:P2_2 */
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_RLIN2_RLIN28RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC

/* Pin:74 Name:P2_3 */
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_RLIN2_RLIN28TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:75 Name:P2_4 */
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_RLIN2_RLIN29RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_ADCA0_ADCA0SEL0_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC

/* Pin:76 Name:P2_5 */
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_RLIN2_RLIN29TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_ADCA0_ADCA0SEL1_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC

/* Pin:77 Name:P2_6 */
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_ADCA0_ADCA0SEL2_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:78 Name:P2_7 */
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_RLIN2_RLIN210RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC

/* Pin:79 Name:P2_8 */
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_RLIN2_RLIN210TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:80 Name:P2_9 */
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_PWGA_PWGA77O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:81 Name:P2_10 */
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_PWGA_PWGA78O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:82 Name:P2_11 */
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_PWGA_PWGA79O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:83 Name:P2_12 */
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_RLIN2_RLIN211RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC

/* Pin:84 Name:P2_13 */
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_RLIN2_RLIN211TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:85 Name:P2_14 */
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_PWGA_PWGA74O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:86 Name:P2_15 */
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_PWGA_PWGA75O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:87 Name:P3_0 */
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_PWGA_PWGA76O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:88 Name:P3_1 */
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_PWGA_PWGA80O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:89 Name:P3_2 */
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_PWGA_PWGA81O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:90 Name:P3_3 */
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_PWGA_PWGA82O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:91 Name:P3_4 */
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_PWGA_PWGA83O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:92 Name:P3_5 */
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_PWGA_PWGA84O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:93 Name:P3_6 */
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_PWGA_PWGA85O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:94 Name:P3_7 */
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_PWGA_PWGA86O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:95 Name:P3_8 */
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_PWGA_PWGA87O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:96 Name:P3_9 */
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:97 Name:P3_10 */
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:98 Name:P8_0 */
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_TAUJ0_TAUJ0I0_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_TAUJ0_TAUJ0O0_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_LPS_DPIN2_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_PWGA_PWGA14O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_INTP_INTP4_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_CSIH0_CSIH0CSS0_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_ADCA0_ADCA0I0S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:99 Name:P8_1 */
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_TAPA_TAPA0ESO_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_TAUJ0_TAUJ0O1_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_LPS_DPIN0_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_PWGA_PWGA15O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_INTP_INTP5_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_CSIH1_CSIH1CSS3_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_ADCA0_ADCA0I1S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:100 Name:P8_2 */
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_TAUJ0_TAUJ0I0_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_TAUJ0_TAUJ0O0_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_LPS_DPIN2_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_CSIH0_CSIH0CSS0_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_INTP_INTP6_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_PWGA_PWGA22O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_ADCA0_ADCA0I4S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:101 Name:P8_3 */
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_TAUJ0_TAUJ0I1_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_TAUJ0_TAUJ0O1_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_LPS_DPIN3_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_CSIH0_CSIH0CSS1_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_INTP_INTP7_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_PWGA_PWGA23O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_ADCA0_ADCA0I5S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:102 Name:P8_4 */
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_TAUJ0_TAUJ0I2_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_TAUJ0_TAUJ0O2_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_LPS_DPIN4_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_CSIH0_CSIH0CSS2_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_INTP_INTP8_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_PWGA_PWGA36O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_ADCA0_ADCA0I6S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:103 Name:P8_5 */
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_TAUJ0_TAUJ0I3_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_TAUJ0_TAUJ0O3_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_CSIH0_CSIH0CSS3_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_INTP_INTP9_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_PWGA_PWGA37O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_ADCA0_ADCA0I7S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:104 Name:P8_6 */
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_INTP_NMI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_CSIH0_CSIH0CSS4_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_PWGA_PWGA38O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_RTCA_RTCA0OUT_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_ADCA0_ADCA0I8S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:105 Name:P8_7 */
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_CSIH3_CSIH3CSS0_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_PWGA_PWGA39O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_ADCA0_ADCA0I14S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:106 Name:P8_8 */
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_CSIH3_CSIH3CSS1_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_PWGA_PWGA40O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_ADCA0_ADCA0I15S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:107 Name:P8_9 */
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_CSIH3_CSIH3CSS2_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_PWGA_PWGA41O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_ADCA0_ADCA0I16S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:108 Name:P8_10 */
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_CSIH3_CSIH3CSS3_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_LPS_DPIN14_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_PWGA_PWGA42O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ADCA0_ADCA0I17S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:109 Name:P8_11 */
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_TAUJ1_TAUJ1I2_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_TAUJ1_TAUJ1O2_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_LPS_DPIN15_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_PWGA_PWGA43O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_CSIH1_CSIH1CSS4_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ADCA0_ADCA0I18S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:110 Name:P8_12 */
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_TAUJ1_TAUJ1I3_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_TAUJ1_TAUJ1O3_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_LPS_DPIN16_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_PWGA_PWGA44O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_CSIH1_CSIH1CSS5_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_ADCA0_ADCA0I19S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:111 Name:P9_0 */
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_INTP_NMI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_PWGA_PWGA8O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_TAUD0_TAUD0I0_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_TAUD0_TAUD0O0_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ADCA0_ADCA0TRG0_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_CSIH2_CSIH2CSS0_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_KR_KR0I4_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ADCA0_ADCA0I2S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:112 Name:P9_1 */
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_INTP_INTP11_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_PWGA_PWGA9O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_TAUD0_TAUD0I2_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_TAUD0_TAUD0O2_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_KR_KR0I5_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_CSIH2_CSIH2CSS1_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_ADCA0_ADCA0I3S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:113 Name:P9_2 */
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_KR_KR0I6_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_PWGA_PWGA20O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_TAPA_TAPA0ESO_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_CSIH2_CSIH2CSS2_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_ADCA0_ADCA0I9S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:114 Name:P9_3 */
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_KR_KR0I7_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_PWGA_PWGA21O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_CSIH2_CSIH2CSS3_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_TAUJ1_TAUJ1I1_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_TAUJ1_TAUJ1O1_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_ADCA0_ADCA0I10S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:115 Name:P9_4 */
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_CSIH0_CSIH0CSS5_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_PWGA_PWGA33O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_TAUJ1_TAUJ1I0_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_TAUJ1_TAUJ1O0_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_ADCA0_ADCA0I11S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:116 Name:P9_5 */
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_CSIH0_CSIH0CSS6_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_PWGA_PWGA34O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_TAUJ1_TAUJ1I1_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_TAUJ1_TAUJ1O1_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_ADCA0_ADCA0I12S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:117 Name:P9_6 */
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_CSIH0_CSIH0CSS7_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_PWGA_PWGA35O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_ADCA0_ADCA0I13S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:118 Name:P10_0 */
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_TAUD0_TAUD0I1_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_TAUD0_TAUD0O1_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_CAN0_CAN0RX_INTP0_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_CSCXFOUT_CSCXFOUT_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_PWGA_PWGA0O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_TAPA_TAPA0UP_PORT_PIN_OUT PORT_FUNC7 SET_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_CSIH1_CSIH1SI_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_MEMC_MEMC0A19_PORT_PIN_OUT PORT_FUNC9 CLEAR_PIPC
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_ETH_ETH0RXCLK_PORT_PIN_IN PORT_FUNC10 CLEAR_PIPC

/* Pin:119 Name:P10_1 */
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_TAUD0_TAUD0I3_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_TAUD0_TAUD0O3_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_CAN0_CAN0TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_PWGA_PWGA1O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_TAPA_TAPA0UN_PORT_PIN_OUT PORT_FUNC7 SET_PIPC
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_CSIH1_CSIH1SC_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_CSIH1_CSIH1SC_PORT_PIN_OUT PORT_FUNC9 SET_PIPC
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_ETH_ETH0RXD0_PORT_PIN_IN PORT_FUNC10 CLEAR_PIPC
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_ETH_ETH0RRXD0_PORT_PIN_IN PORT_FUNC12 CLEAR_PIPC

/* Pin:120 Name:P10_2 */
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_TAUD0_TAUD0I5_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_TAUD0_TAUD0O5_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_RIIC0_RIIC0SDA_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_RIIC0_RIIC0SDA_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_KR_KR0I0_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_PWGA_PWGA2O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_ADCA0_ADCA0TRG0_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_TAPA_TAPA0VP_PORT_PIN_OUT PORT_FUNC7 SET_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_CSIH1_CSIH1SO_PORT_PIN_OUT PORT_FUNC9 SET_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_ETH_ETH0RXD1_PORT_PIN_IN PORT_FUNC10 CLEAR_PIPC
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_ETH_ETH0RRXD1_PORT_PIN_IN PORT_FUNC12 CLEAR_PIPC

/* Pin:121 Name:P10_3 */
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_TAUD0_TAUD0I7_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_TAUD0_TAUD0O7_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_RIIC0_RIIC0SCL_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_RIIC0_RIIC0SCL_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_KR_KR0I1_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_PWGA_PWGA3O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_ADCA0_ADCA0TRG1_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_TAPA_TAPA0VN_PORT_PIN_OUT PORT_FUNC7 SET_PIPC
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_CSIH1__CSIH1SSI_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_MEMC_MEMC0CLK_PORT_PIN_OUT PORT_FUNC9 CLEAR_PIPC

/* Pin:122 Name:P10_4 */
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_TAUD0_TAUD0I9_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_TAUD0_TAUD0O9_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_RLIN2_RLIN21RX_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_KR_KR0I2_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_ADCA0_ADCA0SEL0_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_ADCA0_ADCA0TRG2_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_TAPA_TAPA0WP_PORT_PIN_OUT PORT_FUNC7 SET_PIPC
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_CSIG0__CSIG0SSI_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_ETH_ETH0RXD2_PORT_PIN_IN PORT_FUNC10 CLEAR_PIPC

/* Pin:123 Name:P10_5 */
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_TAUD0_TAUD0I11_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_TAUD0_TAUD0O11_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_RLIN2_RLIN21TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_KR_KR0I3_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_ADCA0_ADCA0SEL1_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_TAPA_TAPA0WN_PORT_PIN_OUT PORT_FUNC7 SET_PIPC
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_CSIG0_CSIG0RYI_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_CSIG0_CSIG0RYO_PORT_PIN_OUT PORT_FUNC9 CLEAR_PIPC
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_ETH_ETH0RXD3_PORT_PIN_IN PORT_FUNC10 CLEAR_PIPC

/* Pin:124 Name:P10_6 */
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_TAUD0_TAUD0I13_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_TAUD0_TAUD0O13_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_CSIG0_CSIG0SO_PORT_PIN_OUT PORT_FUNC3 SET_PIPC
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_ENCA0_ENCA0TIN0_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_ADCA0_ADCA0SEL2_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_CAN1_CAN1RX_INTP1_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_MEMC_MEMC0AD0_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_MEMC_MEMC0AD0_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:125 Name:P10_7 */
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_TAUD0_TAUD0I15_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_TAUD0_TAUD0O15_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_CSIG0_CSIG0SC_PORT_PIN_IN PORT_FUNC2 SET_PIPC
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_CSIG0_CSIG0SC_PORT_PIN_OUT PORT_FUNC3 SET_PIPC
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_ENCA0_ENCA0TIN1_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_PWGA_PWGA4O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_CAN1_CAN1TX_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_MEMC_MEMC0AD1_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_MEMC_MEMC0AD1_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:126 Name:P10_8 */
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_TAUD0_TAUD0I10_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_TAUD0_TAUD0O10_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_CSIG0_CSIG0SI_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_FLX0_FLX0TXDB_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_ENCA0_ENCA0ZIN_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_PWGA_PWGA5O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_MEMC_MEMC0AD2_PORT_PIN_IN PORT_FUNC6 SET_PIPC
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_MEMC_MEMC0AD2_PORT_PIN_OUT PORT_FUNC7 SET_PIPC

/* Pin:127 Name:P10_9 */
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_TAUD0_TAUD0I12_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_TAUD0_TAUD0O12_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_RLIN3_RLIN30RX_INTP10_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_ENCA0_ENCA0AIN_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_PWGA_PWGA6O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_CSIH0_CSIH0RYI_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_CSIH0_CSIH0RYO_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_MEMC_MEMC0AD3_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_MEMC_MEMC0AD3_PORT_PIN_OUT PORT_FUNC9 SET_PIPC
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_FLX0_FLX0RXDB_PORT_PIN_IN PORT_FUNC10 CLEAR_PIPC

/* Pin:128 Name:P10_10 */
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_TAUD0_TAUD0I14_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_TAUD0_TAUD0O14_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_RLIN3_RLIN30TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_ENCA0_ENCA0BIN_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_PWGA_PWGA7O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_CSIH0_CSIH0CSS1_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_MEMC_MEMC0AD4_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_MEMC_MEMC0AD4_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:129 Name:P10_11 */
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_PWGA_PWGA16O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_RLIN3_RLIN31RX_INTP11_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_FLX0_FLX0TXENA_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_CSIH1_CSIH1CSS0_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_TAUB0_TAUB0I1_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_TAUB0_TAUB0O1_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_MEMC_MEMC0AD5_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_MEMC_MEMC0AD5_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:130 Name:P10_12 */
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_PWGA_PWGA17O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_FLX0_FLX0STPWT_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_RLIN3_RLIN31TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_CSIH1_CSIH1CSS1_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_TAUB0_TAUB0I3_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_TAUB0_TAUB0O3_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_MEMC_MEMC0AD6_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_MEMC_MEMC0AD6_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:131 Name:P10_13 */
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_CSIH0__CSIH0SSI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_PWGA_PWGA18O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_RLIN3_RLIN32RX_INTP12_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_FLX0_FLX0TXENB_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_TAUB0_TAUB0I5_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_TAUB0_TAUB0O5_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_MEMC_MEMC0AD7_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_MEMC_MEMC0AD7_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:132 Name:P10_14 */
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_ADCA1_ADCA1TRG0_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_PWGA_PWGA19O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_FLX0_FLX0RXDA_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_RLIN3_RLIN32TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_CSIH3__CSIH3SSI_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_TAUB0_TAUB0I7_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_TAUB0_TAUB0O7_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_MEMC_MEMC0AD8_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_MEMC_MEMC0AD8_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:133 Name:P10_15 */
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_CSIH3_CSIH3RYI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_CSIH3_CSIH3RYO_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_PWGA_PWGA24O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_RLIN2_RLIN22RX_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_TAUB0_TAUB0I9_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_TAUB0_TAUB0O9_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_MEMC__MEMC0RD_PORT_PIN_OUT PORT_FUNC9 CLEAR_PIPC

/* Pin:134 Name:P11_0 */
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_CSIH2_CSIH2RYI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_CSIH2_CSIH2RYO_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_ADCA1_ADCA1TRG2_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_PWGA_PWGA25O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_RLIN2_RLIN22TX_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_TAUB0_TAUB0I11_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_TAUB0_TAUB0O11_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_MEMC__MEMC0WR_PORT_PIN_OUT PORT_FUNC9 CLEAR_PIPC

/* Pin:135 Name:P11_1 */
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_CSIH2__CSIH2SSI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_FLX0_FLX0TXDA_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_RLIN2_RLIN20RX_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_CSIH0_CSIH0CSS7_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_PWGA_PWGA26O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_TAUB0_TAUB0I13_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_TAUB0_TAUB0O13_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_MEMC_MEMC0AD9_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_MEMC_MEMC0AD9_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:136 Name:P11_2 */
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_CSIH2_CSIH2SO_PORT_PIN_OUT PORT_FUNC1 SET_PIPC
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_RLIN2_RLIN20TX_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_PWGA_PWGA27O_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_TAUB0_TAUB0I15_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_TAUB0_TAUB0O15_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_MEMC_MEMC0AD10_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_MEMC_MEMC0AD10_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:137 Name:P11_3 */
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_CSIH2_CSIH2SC_PORT_PIN_IN PORT_FUNC0 SET_PIPC
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_CSIH2_CSIH2SC_PORT_PIN_OUT PORT_FUNC1 SET_PIPC
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_CAN3_CAN3RX_INTP3_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_PWGA_PWGA28O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_TAUB1_TAUB1I1_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_TAUB1_TAUB1O1_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_MEMC_MEMC0AD11_PORT_PIN_IN PORT_FUNC6 SET_PIPC
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_MEMC_MEMC0AD11_PORT_PIN_OUT PORT_FUNC7 SET_PIPC

/* Pin:138 Name:P11_4 */
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_CSIH2_CSIH2SI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_CAN3_CAN3TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_PWGA_PWGA29O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_TAUB1_TAUB1I3_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_TAUB1_TAUB1O3_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_MEMC_MEMC0AD12_PORT_PIN_IN PORT_FUNC6 SET_PIPC
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_MEMC_MEMC0AD12_PORT_PIN_OUT PORT_FUNC7 SET_PIPC

/* Pin:139 Name:P11_5 */
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_CAN5_CAN5RX_INTP5_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_RLIN3_RLIN33TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_PWGA_PWGA30O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_CSIH3_CSIH3SI_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_TAUB1_TAUB1I5_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_TAUB1_TAUB1O5_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_MEMC_MEMC0AD13_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_MEMC_MEMC0AD13_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:140 Name:P11_6 */
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_RLIN3_RLIN33RX_INTP13_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_CAN5_CAN5TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_ADCA1_ADCA1TRG1_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_PWGA_PWGA31O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_CSIH3_CSIH3SO_PORT_PIN_OUT PORT_FUNC5 SET_PIPC
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_TAUB1_TAUB1I7_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_TAUB1_TAUB1O7_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_MEMC_MEMC0AD14_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_MEMC_MEMC0AD14_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:141 Name:P11_7 */
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_INTP_INTP5_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_PWGA_PWGA32O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_CSIH3_CSIH3SC_PORT_PIN_IN PORT_FUNC4 SET_PIPC
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_CSIH3_CSIH3SC_PORT_PIN_OUT PORT_FUNC5 SET_PIPC
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_TAUB1_TAUB1I9_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_TAUB1_TAUB1O9_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_MEMC_MEMC0AD15_PORT_PIN_IN PORT_FUNC8 SET_PIPC
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_MEMC_MEMC0AD15_PORT_PIN_OUT PORT_FUNC9 SET_PIPC

/* Pin:142 Name:P11_8 */
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_CSIG1__CSIG1SSI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_RLIN3_RLIN35TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_PWGA_PWGA48O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_TAUB1_TAUB1I11_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_TAUB1_TAUB1O11_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_MEMC__MEMC0CS0_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:143 Name:P11_9 */
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_CSIG1_CSIG1SO_PORT_PIN_OUT PORT_FUNC1 SET_PIPC
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_RLIN3_RLIN35RX_INTP15_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_PWGA_PWGA49O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_TAUB1_TAUB1I13_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_TAUB1_TAUB1O13_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_MEMC__MEMC0CS1_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:144 Name:P11_10 */
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_CSIG1_CSIG1SC_PORT_PIN_IN PORT_FUNC0 SET_PIPC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_CSIG1_CSIG1SC_PORT_PIN_OUT PORT_FUNC1 SET_PIPC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_PWGA_PWGA50O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_TAUB1_TAUB1I15_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_TAUB1_TAUB1O15_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_MEMC__MEMC0CS2_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_ETH_ETH0COL_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC

/* Pin:145 Name:P11_11 */
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_CSIG1_CSIG1SI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_RLIN2_RLIN25TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_PWGA_PWGA51O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_TAUB1_TAUB1I0_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_TAUB1_TAUB1O0_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_MEMC__MEMC0CS3_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_ETH_ETH0RXDV_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC

/* Pin:146 Name:P11_12 */
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_RLIN2_RLIN25RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_PWGA_PWGA52O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_TAUB1_TAUB1I2_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_TAUB1_TAUB1O2_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_MEMC__MEMC0WAIT_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC

/* Pin:147 Name:P11_13 */
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_RLIN2_RLIN24RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_PWGA_PWGA53O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_TAUB1_TAUB1I4_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_TAUB1_TAUB1O4_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_MEMC__MEMC0BEN0_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_ETH_ETH0CRS_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_ETH_ETH0RCRS_PORT_PIN_IN PORT_FUNC10 CLEAR_PIPC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_CSIG2_CSIG2RYI_PORT_PIN_IN PORT_FUNC12 CLEAR_PIPC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_CSIG2_CSIG2RYO_PORT_PIN_OUT PORT_FUNC13 CLEAR_PIPC

/* Pin:148 Name:P11_14 */
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_RLIN2_RLIN24TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_PWGA_PWGA54O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_TAUB1_TAUB1I6_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_TAUB1_TAUB1O6_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_MEMC__MEMC0BEN1_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_ETH_ETH0RXERR_PORT_PIN_IN PORT_FUNC8 CLEAR_PIPC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_ETH_ETH0RRXERR_PORT_PIN_IN PORT_FUNC10 CLEAR_PIPC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_CSIG2_CSIG2SSI_PORT_PIN_IN PORT_FUNC12 CLEAR_PIPC

/* Pin:149 Name:P11_15 */
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_CAN2_CAN2RX_INTP2_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_CSIH2_CSIH2CSS4_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_PWGA_PWGA55O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_TAUB1_TAUB1I8_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_TAUB1_TAUB1O8_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_MEMC__MEMC0ASTB_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:150 Name:P12_0 */
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_CAN2_CAN2TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_PWGA_PWGA56O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_TAUB1_TAUB1I10_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_TAUB1_TAUB1O10_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_MEMC_MEMC0A16_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:151 Name:P12_1 */
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_RLIN3_RLIN34RX_INTP14_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_CSIH2_CSIH2CSS5_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_PWGA_PWGA57O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_TAUB1_TAUB1I12_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_TAUB1_TAUB1O12_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_MEMC_MEMC0A17_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:152 Name:P12_2 */
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_RLIN3_RLIN34TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_PWGA_PWGA58O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_TAUB1_TAUB1I14_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_TAUB1_TAUB1O14_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_MEMC_MEMC0A18_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:153 Name:P12_3 */
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_RLIN2_RLIN27RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_ETH_ETH0REFCLK_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_PWGA_PWGA68O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_CSIG2_CSIG2SI_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC

/* Pin:154 Name:P12_4 */
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_RLIN2_RLIN27TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_PWGA_PWGA69O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_CSIG2_CSIG2SC_PORT_PIN_IN PORT_FUNC4 SET_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_CSIG2_CSIG2SC_PORT_PIN_OUT PORT_FUNC5 SET_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_ETH_ETH0MDIO_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_ETH_ETH0MDIO_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:155 Name:P12_5 */
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_PWGA_PWGA70O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_ETH_ETH0MDC_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_CSIG2_CSIG2SO_PORT_PIN_OUT PORT_FUNC5 SET_PIPC

/* Pin:156 Name:P13_0 */
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_MEMC_MEMC0A19_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:157 Name:P13_1 */
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:158 Name:P13_2 */
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_ETH_ETH0RXDV_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC

/* Pin:159 Name:P13_3 */
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_ETH_ETH0RXERR_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_ETH_ETH0RRXERR_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC

/* Pin:160 Name:P13_4 */
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:161 Name:P13_5 */
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:162 Name:P13_6 */
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_PWGA_PWGA72O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC

/* Pin:163 Name:P13_7 */
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_PWGA_PWGA73O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC

/* Pin:164 Name:P18_0 */
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_CSIG1_CSIG1RYI_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_CSIG1_CSIG1RYO_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_ETH_ETH0LINK_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_PWGA_PWGA61O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_ADCA1_ADCA1I0S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:165 Name:P18_1 */
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_PWGA_PWGA62O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_ETH_ETH0TXD0_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_ETH_ETH0RTXD0_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_ADCA1_ADCA1I1S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:166 Name:P18_2 */
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_PWGA_PWGA63O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_ETH_ETH0TXD1_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_ETH_ETH0RTXD1_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_ADCA1_ADCA1I2S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:167 Name:P18_3 */
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_PWGA_PWGA71O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_ETH_ETH0TXD2_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_ADCA1_ADCA1I3S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:168 Name:P18_4 */
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_CSIH1_CSIH1CSS4_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_ETH_ETH0TXD3_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_ADCA1_ADCA1I4S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:169 Name:P18_5 */
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_CSIH1_CSIH1CSS5_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_ETH_ETH0TXEN_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_ETH_ETH0RTXEN_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_ADCA1_ADCA1I5S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:170 Name:P18_6 */
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_ETH_ETH0TXERR_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_ADCA1_ADCA1I6S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:171 Name:P18_7 */
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_ETH_ETH0TXCLK_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_ADCA1_ADCA1I7S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:172 Name:P18_8 */
#define PIN_FUNCTION_REG_172_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_172_PORT_PIN_MODE_ETH_ETH0CRS_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_172_PORT_PIN_MODE_ETH_ETH0RCRS_PORT_PIN_IN PORT_FUNC2 CLEAR_PIPC
#define PIN_FUNCTION_REG_172_PORT_PIN_MODE_ADCA1_ADCA1I8S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:173 Name:P18_9 */
#define PIN_FUNCTION_REG_173_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_173_PORT_PIN_MODE_ETH_ETH0COL_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_173_PORT_PIN_MODE_ADCA1_ADCA1I9S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:174 Name:P18_10 */
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_ADCA1_ADCA1I10S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:175 Name:P18_11 */
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_ADCA1_ADCA1I11S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:176 Name:P18_12 */
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ADCA1_ADCA1I12S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:177 Name:P18_13 */
#define PIN_FUNCTION_REG_177_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_177_PORT_PIN_MODE_ADCA1_ADCA1I13S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:178 Name:P18_14 */
#define PIN_FUNCTION_REG_178_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_178_PORT_PIN_MODE_ADCA1_ADCA1I14S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:179 Name:P18_15 */
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_ADCA1_ADCA1I15S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:180 Name:P19_0 */
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_ADCA1_ADCA1I16S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:181 Name:P19_1 */
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_ADCA1_ADCA1I17S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:182 Name:P19_2 */
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_ADCA1_ADCA1I18S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:183 Name:P19_3 */
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_ADCA1_ADCA1I19S_PORT_PIN_IN PORT_FUNC14 CLEAR_PIPC

/* Pin:184 Name:P20_0 */
#define PIN_FUNCTION_REG_184_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_184_PORT_PIN_MODE_RLIN2_RLIN26RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_184_PORT_PIN_MODE_PWGA_PWGA64O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_184_PORT_PIN_MODE_CANP_INTP6_CAN6RX_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_184_PORT_PIN_MODE_CSIG3_CSIG3SI_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC

/* Pin:185 Name:P20_1 */
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_RLIN2_RLIN26TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_PWGA_PWGA65O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_CAN6_CAN6TX_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_CSIG3_CSIG3SO_PORT_PIN_OUT PORT_FUNC7 SET_PIPC

/* Pin:186 Name:P20_2 */
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_CAN4_CAN4RX_INTP4_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_PWGA_PWGA66O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_RLIN2_RLIN29RX_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_CSIG3_CSIG3SC_PORT_PIN_IN PORT_FUNC6 SET_PIPC
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_CSIG3_CSIG3SC_PORT_PIN_OUT PORT_FUNC7 SET_PIPC

/* Pin:187 Name:P20_3 */
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_CAN4_CAN4TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_PWGA_PWGA67O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_RLIN2_RLIN29TX_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_CSIG3_CSIG3RYI_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_CSIG3_CSIG3RYO_PORT_PIN_OUT PORT_FUNC7 CLEAR_PIPC

/* Pin:188 Name:P20_4 */
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_RLIN2_RLIN23RX_PORT_PIN_IN PORT_FUNC0 CLEAR_PIPC
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_PWGA_PWGA59O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_CANP_INTP9_CAN7RX_PORT_PIN_IN PORT_FUNC4 CLEAR_PIPC
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_CSIG3_CSIG3SSI_PORT_PIN_IN PORT_FUNC6 CLEAR_PIPC

/* Pin:189 Name:P20_5 */
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_RLIN2_RLIN23TX_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_PWGA_PWGA60O_PORT_PIN_OUT PORT_FUNC3 CLEAR_PIPC
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_CAN7_CAN7TX_PORT_PIN_OUT PORT_FUNC5 CLEAR_PIPC

/* Pin:190 Name:P20_6 */
#define PIN_FUNCTION_REG_190_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_190_PORT_PIN_MODE_PWGA_PWGA88O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:191 Name:P20_7 */
#define PIN_FUNCTION_REG_191_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_191_PORT_PIN_MODE_PWGA_PWGA89O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:192 Name:P20_8 */
#define PIN_FUNCTION_REG_192_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_192_PORT_PIN_MODE_PWGA_PWGA90O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:193 Name:P20_9 */
#define PIN_FUNCTION_REG_193_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_193_PORT_PIN_MODE_PWGA_PWGA91O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:194 Name:P20_10 */
#define PIN_FUNCTION_REG_194_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_194_PORT_PIN_MODE_PWGA_PWGA92O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:195 Name:P20_11 */
#define PIN_FUNCTION_REG_195_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_195_PORT_PIN_MODE_PWGA_PWGA93O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:196 Name:P20_12 */
#define PIN_FUNCTION_REG_196_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_196_PORT_PIN_MODE_PWGA_PWGA94O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:197 Name:P20_13 */
#define PIN_FUNCTION_REG_197_PORT_PIN_MODE_DIO PORT_MODE
#define PIN_FUNCTION_REG_197_PORT_PIN_MODE_PWGA_PWGA95O_PORT_PIN_OUT PORT_FUNC1 CLEAR_PIPC

/* Pin:198 Name:P20_14 */
#define PIN_FUNCTION_REG_198_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:199 Name:P21_0 */
#define PIN_FUNCTION_REG_199_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:200 Name:P21_1 */
#define PIN_FUNCTION_REG_200_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:201 Name:P21_2 */
#define PIN_FUNCTION_REG_201_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:202 Name:P21_3 */
#define PIN_FUNCTION_REG_202_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:203 Name:P21_4 */
#define PIN_FUNCTION_REG_203_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:204 Name:P22_0 */
#define PIN_FUNCTION_REG_204_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:205 Name:P22_1 */
#define PIN_FUNCTION_REG_205_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:206 Name:P22_2 */
#define PIN_FUNCTION_REG_206_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:207 Name:P22_3 */
#define PIN_FUNCTION_REG_207_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:208 Name:P22_4 */
#define PIN_FUNCTION_REG_208_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:209 Name:P22_5 */
#define PIN_FUNCTION_REG_209_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:210 Name:P22_6 */
#define PIN_FUNCTION_REG_210_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:211 Name:P22_7 */
#define PIN_FUNCTION_REG_211_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:212 Name:P22_8 */
#define PIN_FUNCTION_REG_212_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:213 Name:P22_9 */
#define PIN_FUNCTION_REG_213_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:214 Name:P22_10 */
#define PIN_FUNCTION_REG_214_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:215 Name:P22_11 */
#define PIN_FUNCTION_REG_215_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:216 Name:P22_12 */
#define PIN_FUNCTION_REG_216_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:217 Name:P22_13 */
#define PIN_FUNCTION_REG_217_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:218 Name:P22_14 */
#define PIN_FUNCTION_REG_218_PORT_PIN_MODE_DIO PORT_MODE

/* Pin:219 Name:P22_15 */
#define PIN_FUNCTION_REG_219_PORT_PIN_MODE_DIO PORT_MODE

#endif  /* _RH850F1LPORTS_H*/ 
