$(PROJECT_NAME)_$(CANSM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/CanSM_Cfg.h
$(PROJECT_NAME)_$(CANSM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/CanSM_LCfg.c
$(PROJECT_NAME)_$(CANSM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/CanSM.mk

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(CANSM_MODULE_NAME)_CONFIG_FILES)