$(PROJECT_NAME)_$(BSWM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/BswM_Internal.h
$(PROJECT_NAME)_$(BSWM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/BswM.c
$(PROJECT_NAME)_$(BSWM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/BswM.h
$(PROJECT_NAME)_$(BSWM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/BswM.mk

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(BSWM_MODULE_NAME)_CONFIG_FILES)