$(PROJECT_NAME)_$(CANIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/CanIf_Cfg.h
$(PROJECT_NAME)_$(CANIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/CanIf_Cfg.c
$(PROJECT_NAME)_$(CANIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/CanIf_PBCfg.h
$(PROJECT_NAME)_$(CANIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/CanIf_PBCfg.c
$(PROJECT_NAME)_$(CANIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/CanIf.mk

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(CANIF_MODULE_NAME)_CONFIG_FILES)