$(PROJECT_NAME)_$(COMM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/ComM_Cfg.h
$(PROJECT_NAME)_$(COMM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/ComM_Cfg.c
$(PROJECT_NAME)_$(COMM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/ComM.mk

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(COMM_MODULE_NAME)_CONFIG_FILES)