$(PROJECT_NAME)_$(DCM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Dcm_Cfg.h
$(PROJECT_NAME)_$(DCM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Dcm_LCfg.c
$(PROJECT_NAME)_$(DCM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Dcm.mk

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(DCM_MODULE_NAME)_CONFIG_FILES)