$(PROJECT_NAME)_$(DEM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Dem_Cfg.h
$(PROJECT_NAME)_$(DEM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Dem_LCfg.c
$(PROJECT_NAME)_$(DEM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Dem_A2LTags.c
$(PROJECT_NAME)_$(DEM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Dem_IntErrId.h
$(PROJECT_NAME)_$(DEM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Dem_IntEvtId.h
$(PROJECT_NAME)_$(DEM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Dem_EnableCondId.h
$(PROJECT_NAME)_$(DEM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Dem.mk

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(DEM_MODULE_NAME)_CONFIG_FILES)