$(PROJECT_NAME)_$(DET_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Det_Cfg.h
$(PROJECT_NAME)_$(DET_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Det_Cfg.c
$(PROJECT_NAME)_$(DET_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Det.mk

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(DET_MODULE_NAME)_CONFIG_FILES)