$(PROJECT_NAME)_$(FRIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrIf.mk
$(PROJECT_NAME)_$(FRIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrIf_Cfg.c
$(PROJECT_NAME)_$(FRIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrIf_Cfg.h
$(PROJECT_NAME)_$(FRIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrIf_Lcfg.c
$(PROJECT_NAME)_$(FRIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrIf_PBcfg.c
$(PROJECT_NAME)_$(FRIF_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrIf_PBcfg.h

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(FRIF_MODULE_NAME)_CONFIG_FILES)