$(PROJECT_NAME)_$(FRNM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrNm.mk
$(PROJECT_NAME)_$(FRNM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrNm_Cfg.h
$(PROJECT_NAME)_$(FRNM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrNm_Lcfg.c
$(PROJECT_NAME)_$(FRNM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrNm_PBcfg.c
$(PROJECT_NAME)_$(FRNM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrNm_PBcfg.h

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(FRNM_MODULE_NAME)_CONFIG_FILES)