$(PROJECT_NAME)_$(FRSM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrSM.mk
$(PROJECT_NAME)_$(FRSM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrSM_Cfg.h
$(PROJECT_NAME)_$(FRSM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrSM_Lcfg.c
$(PROJECT_NAME)_$(FRSM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrSM_PBcfg.c
$(PROJECT_NAME)_$(FRSM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/FrSM_PBcfg.h

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(FRSM_MODULE_NAME)_CONFIG_FILES)