$(PROJECT_NAME)_$(NM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Nm.mk
$(PROJECT_NAME)_$(NM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Nm_Cfg.c
$(PROJECT_NAME)_$(NM_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Nm_Cfg.h

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(NM_MODULE_NAME)_CONFIG_FILES)