$(PROJECT_NAME)_$(OS_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Os.mk
$(PROJECT_NAME)_$(OS_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Os.orti
$(PROJECT_NAME)_$(OS_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Os_Cfg.c
$(PROJECT_NAME)_$(OS_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Os_Cfg.h

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(OS_MODULE_NAME)_CONFIG_FILES)