$(PROJECT_NAME)_$(PDUR_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/PduR.mk
$(PROJECT_NAME)_$(PDUR_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/PduR_Cfg.c
$(PROJECT_NAME)_$(PDUR_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/PduR_Cfg.h
$(PROJECT_NAME)_$(PDUR_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/PduR_PbCfg.c
$(PROJECT_NAME)_$(PDUR_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/PduR_PbCfg.h

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(PDUR_MODULE_NAME)_CONFIG_FILES)