$(PROJECT_NAME)_$(RTE_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Rte/Config/Rte.h
$(PROJECT_NAME)_$(RTE_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Rte/Config/Rte.c
$(PROJECT_NAME)_$(RTE_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Rte/Config/Rte_Internal.h
$(PROJECT_NAME)_$(RTE_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Rte/Config/Rte_Internal.c
$(PROJECT_NAME)_$(RTE_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Rte/Config/Rte_Type.h

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(RTE_MODULE_NAME)_CONFIG_FILES)