/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 *
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with
 * the terms contained in the written license agreement between you and ArcCore,
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as
 * published by the Free Software Foundation and appearing in the file
 * LICENSE.GPL included in the packaging of this file or here
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/
#ifndef _MPC5606SPORTDEFS_H
#define _MPC5606SPORTDEFS_H


/* Pad: 0*/
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_SOUND PORT_FUNC3
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 1*/
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 2*/
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 3*/
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 4*/
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 5*/
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 6*/
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 7*/
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 8*/
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_I2C PORT_FUNC3
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 9*/
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_I2C PORT_FUNC3
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 10*/
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 11*/
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 12*/
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 13*/
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 14*/
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 15*/
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 16*/
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_PDI PORT_FUNC2

/* Pad: 17*/
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_PDI PORT_FUNC2

/* Pad: 18*/
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_LIN PORT_FUNC1

/* Pad: 19*/
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_LIN PORT_FUNC1

/* Pad: 20*/
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_ADC PORT_FUNC2

/* Pad: 21*/
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_ADC PORT_FUNC2
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_CONTROL PORT_FUNC3

/* Pad: 22*/
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_ADC PORT_FUNC2
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_CONTROL PORT_FUNC3

/* Pad: 23*/
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_ICU PORT_FUNC2

/* Pad: 24*/
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_ICU PORT_FUNC2

/* Pad: 25*/
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_ICU PORT_FUNC2

/* Pad: 26*/
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_PDI PORT_FUNC2
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 27*/
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_PDI PORT_FUNC2
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 28*/
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 29*/
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 30*/
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 31*/
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 32*/
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 33*/
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 34*/
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 35*/
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 36*/
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 37*/
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 38*/
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 39*/
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 40*/
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_SGL PORT_FUNC2
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 41*/
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_ADC PORT_FUNC2
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 42*/
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_ADC PORT_FUNC2
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 43*/
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_ADC PORT_FUNC2
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 44*/
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 45*/
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 46*/
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 47*/
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 48*/
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 49*/
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 50*/
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 51*/
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 52*/
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 53*/
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 54*/
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_SSD PORT_FUNC2

/* Pad: 55*/
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_SSD PORT_FUNC2

/* Pad: 56*/
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_SSD PORT_FUNC2

/* Pad: 57*/
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_SSD PORT_FUNC2

/* Pad: 58*/
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_SSD PORT_FUNC2

/* Pad: 59*/
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_SSD PORT_FUNC2

/* Pad: 60*/
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_SSD PORT_FUNC2

/* Pad: 61*/
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_SSD PORT_FUNC2

/* Pad: 62*/
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 63*/
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 64*/
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 65*/
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 66*/
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 67*/
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 68*/
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 69*/
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_SMC PORT_FUNC1
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_SSD PORT_FUNC2
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 70*/
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_PDI PORT_FUNC2
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_OTHER PORT_FUNC3
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 71*/
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_PDI PORT_FUNC2
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_OTHER PORT_FUNC3
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 72*/
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_NMI PORT_FUNC1

/* Pad: 73*/
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_PDI PORT_FUNC2
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 74*/
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_PDI PORT_FUNC2
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 75*/
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DCU PORT_FUNC2
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 76*/
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_I2C PORT_FUNC1
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 77*/
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_I2C PORT_FUNC1
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 78*/
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_I2C PORT_FUNC1
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_LIN PORT_FUNC3
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 79*/
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_I2C PORT_FUNC1
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_LIN PORT_FUNC3
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 80*/
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 81*/
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 82*/
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 83*/
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 84*/
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 85*/
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 86*/
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_I2C PORT_FUNC2
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_SGL PORT_FUNC3
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 87*/
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_I2C PORT_FUNC2
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 88*/
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 89*/
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 90*/
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 91*/
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 92*/
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 93*/
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_DCU PORT_FUNC1
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 94*/
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_DCU PORT_FUNC1

/* Pad: 95*/
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_DCU PORT_FUNC1

/* Pad: 96*/
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_DCU PORT_FUNC1

/* Pad: 97*/
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_DCU PORT_FUNC1

/* Pad: 98*/
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_SGL PORT_FUNC2
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_OTHER PORT_FUNC3
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_LCD PORT_GPIO_APC

/* Pad: 99*/
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_JTAG PORT_FUNC1

/* Pad: 100*/
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_JTAG PORT_FUNC1

/* Pad: 101*/
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_JTAG PORT_FUNC1

/* Pad: 102*/
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_JTAG PORT_FUNC1

/* Pad: 103*/
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_CONTROL PORT_FUNC3

/* Pad: 104*/
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_LCD PORT_FUNC1

/* Pad: 105*/
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_PDI PORT_FUNC1

/* Pad: 106*/
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_PDI PORT_FUNC1

/* Pad: 107*/
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_PDI PORT_FUNC1

/* Pad: 108*/
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_PDI PORT_FUNC1

/* Pad: 109*/
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_PDI PORT_FUNC1
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_CAN PORT_FUNC2

/* Pad: 110*/
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_PDI PORT_FUNC1
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_CAN PORT_FUNC2

/* Pad: 111*/
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_PDI PORT_FUNC1
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 112*/
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_PDI PORT_FUNC1
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_ICU PORT_FUNC3

/* Pad: 113*/
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_PDI PORT_FUNC1

/* Pad: 114*/
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_PDI PORT_FUNC1

/* Pad: 115*/
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_PDI PORT_FUNC1

/* Pad: 116*/
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_PDI PORT_FUNC1

/* Pad: 117*/
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_PDI PORT_FUNC1
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_ICU PORT_FUNC2

/* Pad: 118*/
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_PDI PORT_FUNC1
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_ICU PORT_FUNC2

/* Pad: 119*/
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_PDI PORT_FUNC1
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_ICU PORT_FUNC2

/* Pad: 120*/
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_PDI PORT_FUNC1
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_ICU PORT_FUNC2

/* Pad: 121*/
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_PDI PORT_FUNC1
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_DCU PORT_FUNC3

/* Pad: 122*/
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_PDI PORT_FUNC1
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_ICU PORT_FUNC2

/* Pad: 123*/
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_NEXUS PORT_FUNC1
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_PDI PORT_FUNC2

/* Pad: 124*/
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_NEXUS PORT_FUNC1
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_PDI PORT_FUNC2

/* Pad: 125*/
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_NEXUS PORT_FUNC1
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_PDI PORT_FUNC2

/* Pad: 126*/
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_NEXUS PORT_FUNC1
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_PDI PORT_FUNC2

/* Pad: 127*/
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_NEXUS PORT_FUNC1
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_PDI PORT_FUNC2

/* Pad: 128*/
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_NEXUS PORT_FUNC1
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_PDI PORT_FUNC2

/* Pad: 129*/
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_NEXUS PORT_FUNC1
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_PDI PORT_FUNC2

/* Pad: 130*/
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_NEXUS PORT_FUNC1
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_PDI PORT_FUNC2

/* Pad: 131*/
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_I2C PORT_FUNC1
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_ICU PORT_FUNC2

/* Pad: 132*/
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_I2C PORT_FUNC1
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_ICU PORT_FUNC2

/* Input mux selection */
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_17{0, 0}
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_109{0, 1}

#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_26{1, 0}
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_83{1, 1}
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_111{1, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_17{2, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_109{2, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_16{3, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_110{3, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_26{4, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_111{4, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_27{5, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_112{5, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_70{6, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_113{6, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_71{7, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_114{7, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_73{8, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_115{8, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_74{9, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_116{9, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_119{10, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_123{10, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_120{11, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_124{11, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_121{12, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_125{12, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_122{13, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PDI_PAD_126{13, 1}

#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_43{14, 0}
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_79{14, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_69{15, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_91{15, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_98{15, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_15{16, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_68{16, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_75{16, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_14{17, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_67{17, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_74{17, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_13{18, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_66{18, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_73{18, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_12{19, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_65{19, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_71{19, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_11{20, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_64{20, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_70{20, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_63{21, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_132{21, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_6{22, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_62{22, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_131{22, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_7{23, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_27{23, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_80{23, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_5{24, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_122{24, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_4{25, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_121{25, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_3{26, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_120{26, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_2{27, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_119{27, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_1{28, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_71{28, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_112{28, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_0{29, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_70{29, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_111{29, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_26{30, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_98{30, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_53{31, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_82{31, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_103{31, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_52{32, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_90{32, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_117{32, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_9{33, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_29{33, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_51{33, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_28{34, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_50{34, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_88{34, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_10{35, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_25{35, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_49{35, 2}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_118{35, 3}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_24{36, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_48{36, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_89{36, 2}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_23{37, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_47{37, 1}

#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_8{38, 0}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_46{38, 1}
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_81{38, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_69{15, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_91{15, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_98{15, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_15{16, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_68{16, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_75{16, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_14{17, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_67{17, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_74{17, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_13{18, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_66{18, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_73{18, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_12{19, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_65{19, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_71{19, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_11{20, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_64{20, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_70{20, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_63{21, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_132{21, 1}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_6{22, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_62{22, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_131{22, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_7{23, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_27{23, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_80{23, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_5{24, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_122{24, 1}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_4{25, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_121{25, 1}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_3{26, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_120{26, 1}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_2{27, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_119{27, 1}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_1{28, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_112{28, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_0{29, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_111{29, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_26{30, 0}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_53{31, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_82{31, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_103{31, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_52{32, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_90{32, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_117{32, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_9{33, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_29{33, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_51{33, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_28{34, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_50{34, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_88{34, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_10{35, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_25{35, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_49{35, 2}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_118{35, 3}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_24{36, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_48{36, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_89{36, 2}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_23{37, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_47{37, 1}

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_8{38, 0}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_46{38, 1}
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_81{38, 2}

#define INPUT_SELECT_PORT_PIN_MODE_I2C_PAD_79{39, 0}
#define INPUT_SELECT_PORT_PIN_MODE_I2C_PAD_132{39, 1}

#define INPUT_SELECT_PORT_PIN_MODE_I2C_PAD_78{40, 0}
#define INPUT_SELECT_PORT_PIN_MODE_I2C_PAD_131{40, 1}

#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_28{41, 0}
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_78{41, 1}

#define INPUT_SELECT_PORT_PIN_MODE_NEXUS_PAD_126{42, 0}

#endif  /* _MPC5606SPORTDEFS_H*/
