/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 *
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with
 * the terms contained in the written license agreement between you and ArcCore,
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as
 * published by the Free Software Foundation and appearing in the file
 * LICENSE.GPL included in the packaging of this file or here
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

#ifndef _MPC5644APORTS_H
#define _MPC5644APORTS_H


/* Pad: 75*/
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 75*/
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 75*/
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 76*/
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 76*/
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 76*/
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 77*/
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 77*/
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 77*/
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 78*/
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 78*/
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 78*/
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 79*/
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 79*/
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 79*/
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 80*/
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 80*/
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 80*/
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 81*/
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 81*/
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 81*/
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 82*/
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 82*/
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 82*/
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 83*/
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 83*/
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_CAN PORT_FUNC1

/* Pad: 83*/
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 84*/
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 84*/
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_CAN PORT_FUNC1

/* Pad: 84*/
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 85*/
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 85*/
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_CAN PORT_FUNC1

/* Pad: 85*/
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 85*/
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_OTHER0 PORT_FUNC3

/* Pad: 86*/
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 86*/
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_CAN PORT_FUNC1

/* Pad: 86*/
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 86*/
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_OTHER0 PORT_FUNC3

/* Pad: 87*/
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 87*/
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_CAN PORT_FUNC1

/* Pad: 87*/
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 88*/
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 88*/
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_CAN PORT_FUNC1

/* Pad: 88*/
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 89*/
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 89*/
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 89*/
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 90*/
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 90*/
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 90*/
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 91*/
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 91*/
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 91*/
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 92*/
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 92*/
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 92*/
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 98*/
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 98*/
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 99*/
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 99*/
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 102*/
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 102*/
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 102*/
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 103*/
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 103*/
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 103*/
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 104*/
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 104*/
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 104*/
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 105*/
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 105*/
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 105*/
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 106*/
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 106*/
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 106*/
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 107*/
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 107*/
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 107*/
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 108*/
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 108*/
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 108*/
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 109*/
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 109*/
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 109*/
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 110*/
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 110*/
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 110*/
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 114*/
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 114*/
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 114*/
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 114*/
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 115*/
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 115*/
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 115*/
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 116*/
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 116*/
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 116*/
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 117*/
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 117*/
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 117*/
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 118*/
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 118*/
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 118*/
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 118*/
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_FLEXRAY PORT_FUNC4

/* Pad: 119*/
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 119*/
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 119*/
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 119*/
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 119*/
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_FLEXRAY PORT_FUNC4

/* Pad: 120*/
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 120*/
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 120*/
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 120*/
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 120*/
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_FLEXRAY PORT_FUNC4

/* Pad: 121*/
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 121*/
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 121*/
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 121*/
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 121*/
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_OTHER3 PORT_FUNC4

/* Pad: 122*/
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 122*/
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 122*/
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 122*/
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 123*/
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 123*/
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 123*/
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 123*/
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 124*/
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 124*/
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 124*/
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 124*/
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 125*/
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 125*/
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 125*/
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 125*/
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 126*/
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 126*/
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 126*/
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 126*/
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 127*/
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 127*/
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 127*/
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 128*/
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 128*/
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 128*/
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 128*/
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 128*/
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_OTHER2 PORT_FUNC4

/* Pad: 129*/
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 129*/
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 129*/
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 129*/
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 130*/
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 130*/
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 130*/
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 130*/
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 131*/
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 131*/
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 131*/
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 131*/
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 132*/
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 132*/
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 132*/
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 132*/
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 133*/
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 133*/
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 133*/
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 133*/
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 134*/
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 134*/
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 134*/
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 134*/
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 134*/
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_FLEXRAY PORT_FUNC4

/* Pad: 135*/
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 135*/
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 135*/
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 135*/
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 135*/
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_FLEXRAY PORT_FUNC4

/* Pad: 136*/
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 136*/
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 136*/
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 136*/
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 137*/
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 137*/
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 137*/
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 137*/
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 137*/
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_FLEXRAY PORT_FUNC4

/* Pad: 138*/
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 138*/
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 138*/
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 138*/
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 139*/
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 139*/
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 139*/
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 139*/
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 140*/
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 140*/
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 140*/
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 140*/
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 141*/
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 141*/
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 141*/
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 141*/
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 141*/
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_OTHER2 PORT_FUNC4

/* Pad: 142*/
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 142*/
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 142*/
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 142*/
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 143*/
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 143*/
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 143*/
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 143*/
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 144*/
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 144*/
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 144*/
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 144*/
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 145*/
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 145*/
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 145*/
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 145*/
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 179*/
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 179*/
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 179*/
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 179*/
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 180*/
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 180*/
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 180*/
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 181*/
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 181*/
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 181*/
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 181*/
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 182*/
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 182*/
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 182*/
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 183*/
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 183*/
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 183*/
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 183*/
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 185*/
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 185*/
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 185*/
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 186*/
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 186*/
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 186*/
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 187*/
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 187*/
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 187*/
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 187*/
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 188*/
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 188*/
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 188*/
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 188*/
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 189*/
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 189*/
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 189*/
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 189*/
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 190*/
#define PIN_FUNCTION_REG_190_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 190*/
#define PIN_FUNCTION_REG_190_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 190*/
#define PIN_FUNCTION_REG_190_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 190*/
#define PIN_FUNCTION_REG_190_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 191*/
#define PIN_FUNCTION_REG_191_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 191*/
#define PIN_FUNCTION_REG_191_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 191*/
#define PIN_FUNCTION_REG_191_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 191*/
#define PIN_FUNCTION_REG_191_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 192*/
#define PIN_FUNCTION_REG_192_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 192*/
#define PIN_FUNCTION_REG_192_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 192*/
#define PIN_FUNCTION_REG_192_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 193*/
#define PIN_FUNCTION_REG_193_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 193*/
#define PIN_FUNCTION_REG_193_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 193*/
#define PIN_FUNCTION_REG_193_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 193*/
#define PIN_FUNCTION_REG_193_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 194*/
#define PIN_FUNCTION_REG_194_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 194*/
#define PIN_FUNCTION_REG_194_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 194*/
#define PIN_FUNCTION_REG_194_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 202*/
#define PIN_FUNCTION_REG_202_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 202*/
#define PIN_FUNCTION_REG_202_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 206*/
#define PIN_FUNCTION_REG_206_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 207*/
#define PIN_FUNCTION_REG_207_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 208*/
#define PIN_FUNCTION_REG_208_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 208*/
#define PIN_FUNCTION_REG_208_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 208*/
#define PIN_FUNCTION_REG_208_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 208*/
#define PIN_FUNCTION_REG_208_PORT_PIN_MODE_ADC PORT_FUNC3

/* Pad: 212*/
#define PIN_FUNCTION_REG_212_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 212*/
#define PIN_FUNCTION_REG_212_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 212*/
#define PIN_FUNCTION_REG_212_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 212*/
#define PIN_FUNCTION_REG_212_PORT_PIN_MODE_ADC PORT_FUNC3

/* Pad: 213*/
#define PIN_FUNCTION_REG_213_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 213*/
#define PIN_FUNCTION_REG_213_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 213*/
#define PIN_FUNCTION_REG_213_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 213*/
#define PIN_FUNCTION_REG_213_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 215*/
#define PIN_FUNCTION_REG_215_PORT_PIN_MODE_ADC PORT_FUNC0

/* Pad: 215*/
#define PIN_FUNCTION_REG_215_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 215*/
#define PIN_FUNCTION_REG_215_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 215*/
#define PIN_FUNCTION_REG_215_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 216*/
#define PIN_FUNCTION_REG_216_PORT_PIN_MODE_ADC PORT_FUNC0

/* Pad: 216*/
#define PIN_FUNCTION_REG_216_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 216*/
#define PIN_FUNCTION_REG_216_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 216*/
#define PIN_FUNCTION_REG_216_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 217*/
#define PIN_FUNCTION_REG_217_PORT_PIN_MODE_ADC PORT_FUNC0

/* Pad: 217*/
#define PIN_FUNCTION_REG_217_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 217*/
#define PIN_FUNCTION_REG_217_PORT_PIN_MODE_OTHER1 PORT_FUNC2

/* Pad: 217*/
#define PIN_FUNCTION_REG_217_PORT_PIN_MODE_OTHER2 PORT_FUNC3

/* Pad: 218*/
#define PIN_FUNCTION_REG_218_PORT_PIN_MODE_ADC PORT_FUNC1

/* Pad: 218*/
#define PIN_FUNCTION_REG_218_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 218*/
#define PIN_FUNCTION_REG_218_PORT_PIN_MODE_OTHER1 PORT_FUNC3

/* Pad: 219*/
/* NOTE: SIU_PCR219 has no PA field so this here only to be able to use pin as DIO */
#define PIN_FUNCTION_REG_219_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 220*/
#define PIN_FUNCTION_REG_220_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 221*/
#define PIN_FUNCTION_REG_221_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 222*/
#define PIN_FUNCTION_REG_222_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 223*/
#define PIN_FUNCTION_REG_223_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 224*/
#define PIN_FUNCTION_REG_224_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 225*/
#define PIN_FUNCTION_REG_225_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 227*/
#define PIN_FUNCTION_REG_227_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 228*/
#define PIN_FUNCTION_REG_228_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 230*/
#define PIN_FUNCTION_REG_230_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 231*/
#define PIN_FUNCTION_REG_231_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 232*/
#define PIN_FUNCTION_REG_232_PORT_PIN_MODE_OTHER0 PORT_FUNC1

#endif  /* _MPC5644APORTS_H*/ 
