/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 *
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with
 * the terms contained in the written license agreement between you and ArcCore,
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as
 * published by the Free Software Foundation and appearing in the file
 * LICENSE.GPL included in the packaging of this file or here
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

#ifndef _MPC5645SPORTS_H
#define _MPC5645SPORTS_H


/* Pad: 0*/
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_0 {49, 0}
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_0 {26, 0}

/* Pad: 1*/
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_1 {48, 0}
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_1 {25, 0}

/* Pad: 2*/
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 3*/
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 4*/
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 5*/
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 6*/
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 7*/
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 8*/
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_8 {28, 0}

/* Pad: 9*/
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_9 {27, 0}

/* Pad: 10*/
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 11*/
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 12*/
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 13*/
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 14*/
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 15*/
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 16*/
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_LIN PORT_FUNC2

/* Pad: 17*/
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_CAN PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_17 {0, 0}
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_LIN PORT_FUNC2

/* Pad: 18*/
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_LIN PORT_FUNC1

/* Pad: 19*/
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_LIN PORT_FUNC1

/* Pad: 20*/
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 21*/
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 22*/
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 23*/
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_23 {44, 0}
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_OTHER PORT_FUNC3

/* Pad: 24*/
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_24 {43, 0}
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_OTHER PORT_FUNC3

/* Pad: 25*/
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_25 {42, 0}
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_OTHER PORT_FUNC3

/* Pad: 26*/
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_CAN PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_26 {1, 0}
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 27*/
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 28*/
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_28 {34, 0}
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 29*/
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_29 {35, 0}
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 30*/
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 31*/
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 32*/
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 33*/
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 34*/
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 35*/
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 36*/
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 37*/
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 38*/
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 39*/
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 40*/
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 41*/
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 42*/
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 43*/
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_SPI PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_43 {15, 0}

/* Pad: 44*/
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 45*/
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 46*/
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_46 {32, 0}

/* Pad: 47*/
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_47 {40, 0}

/* Pad: 48*/
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_48 {47, 0}

/* Pad: 49*/
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_49 {17, 0}

/* Pad: 50*/
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_50 {16, 0}

/* Pad: 51*/
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_51 {24, 0}

/* Pad: 52*/
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_52 {31, 0}

/* Pad: 53*/
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 54*/
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 55*/
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_55 {17, 1}

/* Pad: 56*/
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_56 {18, 0}

/* Pad: 57*/
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_57 {19, 0}

/* Pad: 58*/
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_58 {20, 0}

/* Pad: 59*/
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_59 {21, 0}

/* Pad: 60*/
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_60 {22, 0}

/* Pad: 61*/
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_61 {23, 0}

/* Pad: 62*/
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 63*/
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 64*/
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 65*/
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 66*/
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 67*/
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 68*/
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 69*/
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 70*/
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_70 {43, 1}
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_OTHER PORT_FUNC3

/* Pad: 71*/
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_71 {44, 1}
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_OTHER PORT_FUNC3

/* Pad: 72*/
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 73*/
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_73 {45, 0}
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_OTHER PORT_FUNC3

/* Pad: 74*/
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_74 {38, 0}
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_74 {49, 1}

/* Pad: 75*/
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_75 {39, 0}
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_OTHER PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_75 {12, 1}

/* Pad: 76*/
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_76 {40, 1}
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_OTHER PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_76 {13, 1}

/* Pad: 77*/
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_77 {39, 1}
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 78*/
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_LIN PORT_FUNC3

/* Pad: 79*/
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_LIN PORT_FUNC3

/* Pad: 80*/
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 81*/
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 82*/
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 83*/
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 84*/
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 85*/
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 86*/
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_86 {29, 0}

/* Pad: 87*/
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_87 {30, 0}

/* Pad: 88*/
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 89*/
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 90*/
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 91*/
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 92*/
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 93*/
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 94*/
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 95*/
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 96*/
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 97*/
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 98*/
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_SPI PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_98 {15, 1}
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 99*/
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 100*/
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 101*/
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 102*/
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 103*/
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_103 {45, 1}
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_OTHER PORT_FUNC3

/* Pad: 104*/
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_104 {11, 0}
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_104 {32, 1}

/* Pad: 105*/
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 106*/
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_106 {33, 0}
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_106 {16, 1}

/* Pad: 107*/
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_107 {38, 1}
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_107 {17, 2}

/* Pad: 108*/
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_108 {30, 1}

/* Pad: 109*/
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_109 {29, 1}
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_109 {31, 1}

/* Pad: 110*/
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_110 {28, 1}
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_110 {24, 1}

/* Pad: 111*/
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_111 {27, 1}
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_111 {23, 1}
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_111 {23, 1}

/* Pad: 112*/
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_112 {26, 1}
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_112 {22, 1}

/* Pad: 113*/
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_113 {25, 1}
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_113 {21, 1}

/* Pad: 114*/
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_114 {46, 0}
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_114 {20, 1}

/* Pad: 115*/
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_115 {41, 0}
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_115 {19, 1}
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_115 {19, 1}

/* Pad: 116*/
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_116 {39, 2}
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_116 {18, 1}

/* Pad: 117*/
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 118*/
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_118 {32, 2}
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_OTHER PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_118 {9, 0}

/* Pad: 119*/
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_119 {41, 1}
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_OTHER PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_119 {3, 0}

/* Pad: 120*/
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_120 {33, 1}
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_OTHER PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_120 {10, 0}

/* Pad: 121*/
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_121 {42, 1}
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_OTHER PORT_FUNC3

/* Pad: 122*/
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_122 {38, 2}
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_OTHER PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_122 {11, 1}

/* Pad: 123*/
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_123 {4, 0}
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_123 {34, 1}

/* Pad: 124*/
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_124 {5, 0}
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_124 {35, 1}

/* Pad: 125*/
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_125 {6, 0}
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_125 {36, 0}

/* Pad: 126*/
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_126 {7, 0}
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_126 {37, 0}

/* Pad: 127*/
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_127 {8, 0}
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_127 {33, 2}

/* Pad: 128*/
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_LIN PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_128 {51, 0}
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 129*/
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 130*/
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 131*/
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_131 {49, 2}
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_131 {36, 1}

/* Pad: 132*/
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_132 {37, 1}

/* Pad: 133*/
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_CAN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_133 {1, 1}

/* Pad: 134*/
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_CAN PORT_FUNC2

/* Pad: 135*/
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_CAN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_135 {0, 1}
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_135 {46, 1}

/* Pad: 136*/
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_136 {47, 1}

/* Pad: 137*/
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_137 {9, 1}

/* Pad: 138*/
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_138 {10, 1}

/* Pad: 139*/
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_139 {11, 2}
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_139 {42, 2}

/* Pad: 140*/
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_140 {12, 2}
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_140 {43, 2}

/* Pad: 141*/
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_141 {13, 2}
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_141 {44, 2}

/* Pad: 142*/
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_142 {3, 2}
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_142 {45, 2}

/* Pad: 143*/
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_143 {34, 2}
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 144*/
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_144 {35, 2}
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 145*/
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_145 {36, 2}
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 146*/
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_146 {37, 2}
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 147*/
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 148*/
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 149*/
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_ICU PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_149 {41, 2}
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_OTHER PORT_FUNC2

/* Pad: 150*/
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_CAN PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_150 {2, 0}
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_150 {52, 0}
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_OTHER PORT_FUNC3

/* Pad: 151*/
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_LIN PORT_FUNC2
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_OTHER PORT_FUNC3

/* Pad: 152*/
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_152 {9, 2}
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_152 {46, 2}

/* Pad: 153*/
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_ICU PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_153 {47, 2}

/* Pad: 154*/
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_154 {12, 0}
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_154 {40, 2}

/* Pad: 155*/
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_155 {13, 0}
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_155 {47, 3}

/* Pad: 156*/
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_156 {3, 2}
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_156 {16, 2}

/* Pad: 157*/
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_LIN PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_157 {51, 1}
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_CAN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_157 {2, 1}
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_157 {24, 2}

/* Pad: 158*/
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_158 {31, 2}

/* Pad: 159*/
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 160*/
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 161*/
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 162*/
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 163*/
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_163 {51, 2}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_163 {4, 0}

/* Pad: 164*/
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_164 {5, 0}

/* Pad: 165*/
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 166*/
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 167*/
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 168*/
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 169*/
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 170*/
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_OTHER PORT_FUNC1

/* Pad: 171*/
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_171 {52, 1}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_171 {6, 1}

/* Pad: 172*/
#define PIN_FUNCTION_REG_172_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_172_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_172_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_172 {7, 1}

/* Pad: 173*/
#define PIN_FUNCTION_REG_173_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_173_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_173_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_173_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_173 {25, 2}

/* Pad: 174*/
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_174 {26, 2}

/* Pad: 175*/
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_175 {27, 2}

/* Pad: 176*/
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_176 {28, 2}

/* Pad: 177*/
#define PIN_FUNCTION_REG_177_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_177_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_177_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_177_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_177 {29, 2}

/* Pad: 178*/
#define PIN_FUNCTION_REG_178_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_178_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_178_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_178_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_178 {30, 2}

/* Pad: 179*/
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_CAN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_179 {2, 2}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_179 {8, 1}

/* Pad: 180*/
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_CAN PORT_FUNC2

/* Pad: 181*/
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_181 {19, 2}

/* Pad: 182*/
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_182 {21, 2}

/* Pad: 183*/
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_ICU PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_183 {23, 2}

/* Pad: 184*/
#define PIN_FUNCTION_REG_184_PORT_PIN_MODE_DIO PORT_FUNC0

#endif  /* _MPC5645SPORTS_H*/ 
