/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 *
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with
 * the terms contained in the written license agreement between you and ArcCore,
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as
 * published by the Free Software Foundation and appearing in the file
 * LICENSE.GPL included in the packaging of this file or here
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

#ifndef _MPC5668PORTS_H
#define _MPC5668PORTS_H

/* Pin:0 Name:PA0 */
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:1 Name:PA1 */
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:2 Name:PA2 */
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:3 Name:PA3 */
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:4 Name:PA4 */
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:5 Name:PA5 */
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:6 Name:PA6 */
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:7 Name:PA7 */
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:8 Name:PA8 */
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:9 Name:PA9 */
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:10 Name:PA10 */
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:11 Name:PA11 */
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:12 Name:PA12 */
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:13 Name:PA13 */
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:14 Name:PA14 */
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_OTHER3 PORT_FUNC2 

/* Pin:15 Name:PA15 */
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_OTHER3 PORT_FUNC2 

/* Pin:16 Name:PB0 */
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:17 Name:PB1 */
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:18 Name:PB2 */
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:19 Name:PB3 */
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:20 Name:PB4 */
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:21 Name:PB5 */
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:22 Name:PB6 */
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:23 Name:PB7 */
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:24 Name:PB8 */
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_SPI_A PORT_FUNC2 

/* Pin:25 Name:PB9 */
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_SPI_A PORT_FUNC2 

/* Pin:26 Name:PB10 */
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_SPI_B PORT_FUNC2 

/* Pin:27 Name:PB11 */
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_SPI_B PORT_FUNC2 

/* Pin:28 Name:PB12 */
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_SPI_C PORT_FUNC2 

/* Pin:29 Name:PB13 */
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_SPI_C PORT_FUNC2 

/* Pin:30 Name:PB14 */
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_SPI_D PORT_FUNC2 

/* Pin:31 Name:PB15 */
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_SPI_D PORT_FUNC2 

/* Pin:32 Name:PC0 */
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:33 Name:PC1 */
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:34 Name:PC2 */
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_OTHER3 PORT_FUNC2 

/* Pin:35 Name:PC3 */
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_OTHER3 PORT_FUNC2 

/* Pin:36 Name:PC4 */
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_ADC PORT_FUNC1 

/* Pin:37 Name:PC5 */
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_OTHER3 PORT_FUNC2 

/* Pin:38 Name:PC6 */
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_OTHER3 PORT_FUNC2 

/* Pin:39 Name:PC7 */
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_FLEXRAY PORT_FUNC2 

/* Pin:40 Name:PC8 */
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_FLEXRAY PORT_FUNC2 

/* Pin:41 Name:PC9 */
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_FLEXRAY PORT_FUNC2 

/* Pin:42 Name:PC10 */
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_FLEXRAY PORT_FUNC2 

/* Pin:43 Name:PC11 */
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_OTHER3 PORT_FUNC2 

/* Pin:44 Name:PC12 */
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_OTHER3 PORT_FUNC2 

/* Pin:45 Name:PC13 */
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_OTHER PORT_FUNC3 

/* Pin:46 Name:PC14 */
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_OTHER PORT_FUNC2 

/* Pin:47 Name:PC15 */
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_ADC PORT_FUNC1 
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_OTHER PORT_FUNC2 

/* Pin:48 Name:PD0 */
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_CAN PORT_FUNC1 

/* Pin:49 Name:PD1 */
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_CAN PORT_FUNC1 

/* Pin:50 Name:PD2 */
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_CAN PORT_FUNC1 

/* Pin:51 Name:PD3 */
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_CAN PORT_FUNC1 

/* Pin:52 Name:PD4 */
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_CAN PORT_FUNC1 

/* Pin:53 Name:PD5 */
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_CAN PORT_FUNC1 

/* Pin:54 Name:PD6 */
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_CAN PORT_FUNC1 
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_OTHER3 PORT_FUNC3 

/* Pin:55 Name:PD7 */
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_CAN PORT_FUNC1 
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_OTHER3 PORT_FUNC3 

/* Pin:56 Name:PD8 */
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_CAN PORT_FUNC1 
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_OTHER3 PORT_FUNC3 

/* Pin:57 Name:PD9 */
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_CAN PORT_FUNC1 
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_OTHER3 PORT_FUNC3 

/* Pin:58 Name:PD10 */
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_CAN PORT_FUNC1 
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_OTHER3 PORT_FUNC3 

/* Pin:59 Name:PD11 */
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_CAN PORT_FUNC1 
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_OTHER3 PORT_FUNC3 

/* Pin:60 Name:PD12 */
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_OTHER1 PORT_FUNC1 

/* Pin:61 Name:PD13 */
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_OTHER1 PORT_FUNC1 

/* Pin:62 Name:PD14 */
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_OTHER1 PORT_FUNC1 

/* Pin:63 Name:PD15 */
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_OTHER1 PORT_FUNC1 

/* Pin:64 Name:PE0 */
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_PWM PORT_FUNC2 

/* Pin:65 Name:PE1 */
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_PWM PORT_FUNC2 

/* Pin:66 Name:PE2 */
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_PWM PORT_FUNC2 

/* Pin:67 Name:PE3 */
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_PWM PORT_FUNC2 

/* Pin:68 Name:PE4 */
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_PWM PORT_FUNC2 

/* Pin:69 Name:PE5 */
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_PWM PORT_FUNC2 

/* Pin:70 Name:PE6 */
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_PWM PORT_FUNC2 

/* Pin:71 Name:PE7 */
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_PWM PORT_FUNC2 

/* Pin:72 Name:PE8 */
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_SPI_A PORT_FUNC2 

/* Pin:73 Name:PE9 */
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_SPI_A PORT_FUNC2 

/* Pin:74 Name:PE10 */
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_SPI_B PORT_FUNC2 

/* Pin:75 Name:PE11 */
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_SPI_B PORT_FUNC2 

/* Pin:76 Name:PE12 */
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_SPI_C PORT_FUNC2 

/* Pin:77 Name:PE13 */
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_OTHER1 PORT_FUNC1 
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_SPI_C PORT_FUNC2 

/* Pin:78 Name:PE14 */
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_OTHER3 PORT_FUNC1 
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_SPI_D PORT_FUNC2 

/* Pin:79 Name:PE15 */
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_OTHER3 PORT_FUNC1 
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_SPI_D PORT_FUNC2 

/* Pin:80 Name:PF0 */
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_OTHER0 PORT_FUNC1 

/* Pin:81 Name:PF1 */
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_SPI_A PORT_FUNC1 

/* Pin:82 Name:PF2 */
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_SPI_A PORT_FUNC1 

/* Pin:83 Name:PF3 */
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_SPI_A PORT_FUNC1 
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_SPI_B PORT_FUNC2 
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_SPI_C PORT_FUNC3 

/* Pin:84 Name:PF4 */
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_OTHER0 PORT_FUNC1 
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_SPI_A PORT_FUNC2 
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_SPI_C PORT_FUNC3 

/* Pin:85 Name:PF5 */
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_SPI_B PORT_FUNC1 
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_SPI_A PORT_FUNC2 
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_SPI_C PORT_FUNC3 

/* Pin:86 Name:PF6 */
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_SPI_B PORT_FUNC1 
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_SPI_A PORT_FUNC2 
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_SPI_C PORT_FUNC3 

/* Pin:87 Name:PF7 */
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_SPI_B PORT_FUNC1 
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_SPI_C PORT_FUNC2 
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_SPI_D PORT_FUNC3 

/* Pin:88 Name:PF8 */
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_OTHER0 PORT_FUNC1 

/* Pin:89 Name:PF9 */
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_SPI_C PORT_FUNC1 

/* Pin:90 Name:PF10 */
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_SPI_C PORT_FUNC1 

/* Pin:91 Name:PF11 */
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_SPI_C PORT_FUNC1 
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_SPI_D PORT_FUNC2 
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_SPI_A PORT_FUNC3 

/* Pin:92 Name:PF12 */
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_OTHER0 PORT_FUNC1 

/* Pin:93 Name:PF13 */
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_SPI_D PORT_FUNC1 

/* Pin:94 Name:PF14 */
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_SPI_D PORT_FUNC1 

/* Pin:95 Name:PF15 */
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_SPI_D PORT_FUNC1 
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_SPI_A PORT_FUNC2 
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_SPI_B PORT_FUNC3 

/* Pin:96 Name:PG0 */
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_SPI_A PORT_FUNC1 
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_SPI_B PORT_FUNC2 
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:97 Name:PG1 */
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_SPI_A PORT_FUNC1 
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_SPI_B PORT_FUNC2 
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:98 Name:PG2 */
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_SPI_D PORT_FUNC1 
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_OTHER3 PORT_FUNC2 
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:99 Name:PG3 */
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_SPI_D PORT_FUNC1 
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_OTHER3 PORT_FUNC2 
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:100 Name:PG4 */
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_SPI_D PORT_FUNC1 
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_OTHER3 PORT_FUNC2 
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:101 Name:PG5 */
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_SPI_D PORT_FUNC1 
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_OTHER3 PORT_FUNC2 
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:102 Name:PG6 */
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_SPI_C PORT_FUNC1 
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_ETH PORT_FUNC2 
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:103 Name:PG7 */
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_SPI_C PORT_FUNC1 
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_ETH PORT_FUNC2 
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:104 Name:PG8 */
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_ETH PORT_FUNC2 
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:105 Name:PG9 */
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_ETH PORT_FUNC2 
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:106 Name:PG10 */
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_ETH PORT_FUNC2 
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:107 Name:PG11 */
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_ETH PORT_FUNC2 
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:108 Name:PF12 */
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ETH PORT_FUNC2 
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:109 Name:PG13 */
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ETH PORT_FUNC2 
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:110 Name:PG14 */
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_ETH PORT_FUNC2 
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:111 Name:PG15 */
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ETH PORT_FUNC2 
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ADC PORT_FUNC3 

/* Pin:112 Name:PH0 */
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_ETH PORT_FUNC2 

/* Pin:113 Name:PH1 */
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_ETH PORT_FUNC2 

/* Pin:114 Name:PH2 */
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_ETH PORT_FUNC2 

/* Pin:114 Name:PH4 */
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_ETH PORT_FUNC2 

/* Pin:115 Name:PH3 */
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_ETH PORT_FUNC2 

/* Pin:117 Name:PH5 */
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_ETH PORT_FUNC2 

/* Pin:118 Name:PH6 */
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_ETH PORT_FUNC2 

/* Pin:119 Name:PH7 */
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_ETH PORT_FUNC2 

/* Pin:120 Name:PH8 */
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:121 Name:PH9 */
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:122 Name:PH10 */
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:123 Name:PH11 */
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:124 Name:PH12 */
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:125 Name:PH13 */
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:126 Name:PH14 */
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:127 Name:PH15 */
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:128 Name:PJ0 */
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_SPI_A PORT_FUNC2 

/* Pin:129 Name:PJ1 */
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_SPI_A PORT_FUNC2 

/* Pin:130 Name:PJ2 */
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_SPI_B PORT_FUNC2 

/* Pin:131 Name:PJ3 */
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_SPI_B PORT_FUNC2 

/* Pin:132 Name:PJ4 */
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_SPI_C PORT_FUNC2 

/* Pin:133 Name:PJ5 */
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_SPI_C PORT_FUNC2 

/* Pin:134 Name:PJ6 */
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_SPI_D PORT_FUNC2 

/* Pin:135 Name:PJ7 */
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_SPI_D PORT_FUNC2 

/* Pin:136 Name:PJ8 */
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:137 Name:PJ9 */
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:138 Name:PJ10 */
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:139 Name:PJ11 */
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:140 Name:PJ12 */
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:141 Name:PJ13 */
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:142 Name:PJ14 */
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:143 Name:PJ15 */
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_PWM PORT_FUNC1 

/* Pin:144 Name:PK0 */
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_OTHER2 PORT_FUNC1 
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_OTHER3 PORT_FUNC3 

/* Pin:145 Name:PK1 */
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_OTHER2 PORT_FUNC1 
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_SPI_B PORT_FUNC2 
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_SPI_D PORT_FUNC3 

/* Pin:146 Name:PK2 */
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_OTHER2 PORT_FUNC1 
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_SPI_B PORT_FUNC2 
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_SPI_D PORT_FUNC3 

/* Pin:147 Name:PK3 */
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_FLEXRAY PORT_FUNC1 
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_OTHER PORT_FUNC2 
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_SPI_C PORT_FUNC3 

/* Pin:148 Name:PK4 */
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_FLEXRAY PORT_FUNC1 
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_OTHER PORT_FUNC2 
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_SPI_C PORT_FUNC3 

/* Pin:149 Name:PK5 */
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_FLEXRAY PORT_FUNC1 
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_OTHER PORT_FUNC2 
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_SPI_C PORT_FUNC3 

/* Pin:150 Name:PK6 */
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_FLEXRAY PORT_FUNC1 
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_SPI_B PORT_FUNC2 
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_SPI_C PORT_FUNC3 

/* Pin:151 Name:PK7 */
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_FLEXRAY PORT_FUNC1 
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_SPI_B PORT_FUNC2 
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_SPI_C PORT_FUNC3 

/* Pin:152 Name:PK8 */
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_FLEXRAY PORT_FUNC1 
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_SPI_B PORT_FUNC2 
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_SPI_A PORT_FUNC3 

/* Pin:153 Name:PK9 */
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_OTHER3 PORT_FUNC1 
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_SPI_D PORT_FUNC2 
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_SPI_A PORT_FUNC3 
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_OTHER_A PORT_FUNC4 

/* Pin:154 Name:PK10 */
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_DIO PORT_FUNC0 
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_SPI_B PORT_FUNC1 
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_SPI_D PORT_FUNC2 
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_SPI_A PORT_FUNC3 

#endif  /* _MPC5668PORTS_H*/ 
