/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 *
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with
 * the terms contained in the written license agreement between you and ArcCore,
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as
 * published by the Free Software Foundation and appearing in the file
 * LICENSE.GPL included in the packaging of this file or here
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

#ifndef _MPC5604BPORTS_H
#define _MPC5604BPORTS_H

#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_3 {13, 0}
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_4 {14, 0}
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_5 {15, 0}
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_6 {16, 0}
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_LIN PORT_FUNC2
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_7 {17, 0}
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_8 {31, 0}
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_10 {18, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_10 {30, 0}
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_11 {19, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_11 {29, 0}
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_SPI PORT_FUNC0
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_14 {5, 0}
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_14 {6, 0}
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_15 {5, 1}
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_15 {6, 1}
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_18 {30, 1}
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_19 {29, 1}
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_27 {13, 1}
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_27 {6, 2}
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_28 {14, 1}
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_29 {15, 1}
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_30 {16, 1}
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_31 {17, 1}
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_34 {7, 0}
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_ADC PORT_FUNC2
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_OTHER PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_35 {0, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_35 {3, 0}
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_35 {9, 0}
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_SPI PORT_FUNC0
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_CAN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_36 {8, 0}
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_36 {2, 0}
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_LIN PORT_FUNC0
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_LIN PORT_FUNC0
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_CAN0 PORT_FUNC2
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_OTHER PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_43 {0, 1}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_43 {3, 1}
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_SPI PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_44 {20, 0}
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_44 {11, 0}
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_45 {21, 0}
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_46 {22, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_46 {10, 0}
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_47 {12, 0}
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_60 {25, 0}
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_61 {26, 0}
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_61 {9, 1}
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_62 {27, 0}
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_63 {28, 0}
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_64 {4, 0}
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_SPI PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_66 {8, 1}
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_68 {7, 1}
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_ADC PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_69 {9, 2}
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_ADC PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_70 {23, 0}
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_ADC PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_71 {24, 0}
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_CAN0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_72 {23, 1}
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_CAN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_73 {24, 1}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_73 {2, 1}
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_73 {1, 0}
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_LIN PORT_FUNC0
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_OTHER PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_75 {31, 1}
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_SPI PORT_FUNC0
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_76 {11, 1}
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_78 {10, 1}
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_79 {12, 1}
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_80 {18, 1}
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_81 {19, 1}
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_82 {20, 1}
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_82 {12, 2}
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_83 {21, 1}
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_84 {22, 1}
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_85 {23, 2}
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_86 {24, 2}
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_CAN0 PORT_FUNC3
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_OTHER PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_89 {1, 1}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_89 {2, 2}
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_CAN0 PORT_FUNC3
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_OTHER PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_95 {0, 2}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_95 {3, 2}
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_97 {4, 1}
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_104 {12, 3}
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_105 {10, 2}
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_106 {25, 1}
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_107 {26, 1}
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_108 {27, 1}
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_OTHER PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER_PAD_109 {28, 1}
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_SPI PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_112 {8, 2}
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_114 {7, 2}
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_115 {9, 3}
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_OTHER1 PORT_FUNC2
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_OTHER PORT_FUNC2


#endif  /* _MPC5604BPORTS_H */
