/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 *
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with
 * the terms contained in the written license agreement between you and ArcCore,
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as
 * published by the Free Software Foundation and appearing in the file
 * LICENSE.GPL included in the packaging of this file or here
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

#ifndef _SPC56XL70PORTS_H
#define _SPC56XL70PORTS_H


/* Pad: 0*/
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_0 {35, 0}
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_0 {1, 0}

/* Pad: 1*/
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_1 {36, 0}
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 2*/
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_2 {37, 0}
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_PWM PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_2 {23, 0}
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_SPI PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_2 {2, 0}

/* Pad: 3*/
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_3 {38, 0}
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_3 {3, 0}
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_PWM PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_3 {27, 0}

/* Pad: 4*/
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_4 {9, 0}
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_4 {7, 0}

/* Pad: 5*/
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_5 {14, 0}
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_OTHER0 PORT_FUNC3

/* Pad: 6*/
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 7*/
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_CAN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_7 {43, 0}

/* Pad: 8*/
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_CAN PORT_FUNC2


/* Pad: 9*/
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_PWM PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_9 {27, 1}
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_9 {16, 0}

/* Pad: 10*/
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_SPI PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_10 {3, 1}
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_10 {24, 0}
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_10 {29, 0}

/* Pad: 11*/
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_SPI PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_11 {1, 1}
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_11 {20, 0}
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_11 {22, 0}

/* Pad: 12*/
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_12 {22, 1}
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_12 {26, 0}

/* Pad: 13*/
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_13 {26, 1}
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_SPI PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_13 {2, 1}
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_13 {16, 1}

/* Pad: 14*/
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_14 {13, 0}

/* Pad: 15*/
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_15 {14, 1}
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_CAN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_15 {34, 0}
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_15 {33, 0}

/* Pad: 16*/
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_16 {11, 0}

/* Pad: 17*/
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_17 {12, 0}
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_CAN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_17 {33, 1}
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_17 {34, 1}

/* Pad: 18*/
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_LIN PORT_FUNC1

/* Pad: 19*/
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_19 {31, 0}

/* Pad: 20*/
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 21*/
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 22*/
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 23*/
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_23 {31, 1}
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 24*/
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_GPT PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_24 {8, 2}
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 25*/
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 26*/
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 27*/
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 28*/
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 29*/
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_29 {32, 0}
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 30*/
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_GPT PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_30 {7, 2}
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 31*/
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 32*/
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 33*/
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 34*/
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 36*/
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_36 {28, 0}

/* Pad: 37*/
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_PWM PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_37 {19, 0}

/* Pad: 38*/
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_38 {25, 0}

/* Pad: 39*/
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_PWM PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_39 {21, 0}
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 42*/
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_PWM PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_42 {23, 1}
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_42 {17, 0}

/* Pad: 43*/
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_43 {7, 1}
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 44*/
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_44 {8, 0}
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 45*/
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_45 {10, 0}
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_PWM PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_45 {15, 0}

/* Pad: 46*/
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_46 {11, 1}

/* Pad: 47*/
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_FLEXRAY PORT_FUNC1
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_47 {9, 1}
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_PWM PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_47 {21, 1}
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_47 {15, 1}

/* Pad: 48*/
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_FLEXRAY PORT_FUNC1
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_48 {10, 1}
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_PWM PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_48 {25, 1}

/* Pad: 49*/
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_49 {11, 2}

/* Pad: 50*/
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_50 {12, 1}
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_PWM PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_50 {30, 0}

/* Pad: 51*/
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_FLEXRAY PORT_FUNC1
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_51 {13, 1}
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_PWM PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_51 {23, 2}

/* Pad: 52*/
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_FLEXRAY PORT_FUNC1
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_52 {14, 2}
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_PWM PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_52 {27, 2}

/* Pad: 53*/
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_PWM PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_53 {18, 0}

/* Pad: 54*/
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_PWM PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_54 {30, 1}
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_54 {17, 1}

/* Pad: 55*/
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_OTHER0 PORT_FUNC3

/* Pad: 56*/
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_56 {13, 2}
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_PWM PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_56 {19, 1}

/* Pad: 57*/
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_LIN PORT_FUNC2

/* Pad: 58*/
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_58 {20, 1}
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_GPT PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_58 {35, 1}

/* Pad: 59*/
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_59 {24, 1}
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_GPT PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_59 {36, 1}

/* Pad: 60*/
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_60 {28, 1}
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_60 {32, 1}

/* Pad: 62*/
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_62 {25, 2}
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_GPT PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_62 {38, 1}

/* Pad: 64*/
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 66*/
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 68*/
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 69*/
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 70*/
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 71*/
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 73*/
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 74*/
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 75*/
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 76*/
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_ADC PORT_GPIO_APC

/* Pad: 77*/
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_77 {8, 1}
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 78*/
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_78 {14, 3}

/* Pad: 79*/
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 80*/
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_80 {21, 2}
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_GPT PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_80 {37, 1}

/* Pad: 83*/
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 84*/
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 85*/
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 86*/
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 87*/
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 88*/
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 89*/
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 90*/
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 91*/
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 92*/
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_92 {12, 2}

/* Pad: 93*/
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_93 {13, 3}

/* Pad: 94*/
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_CAN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_94 {43, 1}

/* Pad: 95*/
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_95 {32, 2}
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_CAN PORT_FUNC2

/* Pad: 98*/
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_98 {29, 1}
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 99*/
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_99 {22, 2}
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_GPT PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_99 {7, 3}

/* Pad: 100*/
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_100 {26, 2}
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_GPT PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_100 {8, 3}

/* Pad: 101*/
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_101 {30, 2}
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 102*/
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_102 {23, 3}

/* Pad: 103*/
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_PWM PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_103 {27, 3}

/* Pad: 104*/
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_FLEXRAY PORT_FUNC1
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_PWM PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_104 {16, 2}

/* Pad: 105*/
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_FLEXRAY PORT_FUNC1
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_PWM PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_105 {17, 2}

/* Pad: 106*/
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_FLEXRAY PORT_FUNC1
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_PWM PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_106 {18, 1}

/* Pad: 107*/
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_FLEXRAY PORT_FUNC1
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_PWM PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_107 {19, 2}

/* Pad: 108*/
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 109*/
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 110*/
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 111*/
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 112*/
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 113*/
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 114*/
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 115*/
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 116*/
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_116 {39, 0}

/* Pad: 117*/
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 118*/
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 119*/
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_119 {40, 0}

/* Pad: 120*/
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 121*/
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_SPI PORT_FUNC3

/* Pad: 122*/
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_GPT PORT_FUNC2

/* Pad: 123*/
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_PWM PORT_FUNC1

/* Pad: 124*/
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_PWM PORT_FUNC1

/* Pad: 125*/
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_GPT PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_125 {42, 0}

/* Pad: 126*/
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_GPT PORT_FUNC2

/* Pad: 127*/
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_GPT PORT_FUNC2

/* Pad: 128*/
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_128 {39, 1}
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 129*/
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_129 {40, 1}
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 130*/
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_130 {41, 1}
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 131*/
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_GPT PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_GPT_PAD_131 {42, 1}
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_SPI PORT_FUNC2

#endif  /* _SPC56XL70PORTS_H */
