/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 *
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with
 * the terms contained in the written license agreement between you and ArcCore,
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as
 * published by the Free Software Foundation and appearing in the file
 * LICENSE.GPL included in the packaging of this file or here
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

#ifndef _SPC560B54PORTS_H
#define _SPC560B54PORTS_H

#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_0 {21, 2}  /* E0UC[13] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU0_PAD_0 {38, 0}  /* E0UC[0] / eMIOS_0 */
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_ICU0 PORT_FUNC1
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_OTHER1 PORT_FUNC3
#define PIN_FUNCTION_REG_0_PORT_PIN_MODE_OTHER2 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_1 {39, 0}  /* E0UC[1] / eMIOS_0 */
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_1_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_2_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_3 {13, 0}  /* E1UC[3] / eMIOS_0 */
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_LIN PORT_FUNC2
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_OTHER1 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_4 {14, 0}  /* E0UC[4] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_4 {60, 0}  /* LIN5RX / LINFlex _5 */
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_LIN PORT_FUNC0
#define PIN_FUNCTION_REG_4_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_5 {15, 0}  /* E0UC[5] / eMIOS_0 */
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_5_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_6 {16, 0}  /* E0UC[6] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_6 {59, 0}  /* LIN4RX / LINFlex _4Reserved */
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_6_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_7 {17, 0}  /* E0UC[7] / eMIOS_0 */
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_LIN PORT_FUNC2
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_OTHER1 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_8 {22, 2}  /* E0UC[14] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_8 {31, 0}  /* LIN3RX / LINFlex_3 */
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_OTHER0 PORT_FUNC2  /* Can be used for PWM and ICU */
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_OTHER2 PORT_FUNC0
#define PIN_FUNCTION_REG_8_PORT_PIN_MODE_LIN PORT_FUNC0
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_9_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_10 {18, 0}  /* E0UC[10] / eMIOS_0 */
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_LIN PORT_FUNC3
#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_OTHER1 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_11 {19, 0}  /* E0UC[11] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_11 {58, 1}  /* LIN2RX / LINFlex _2 */
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_LIN PORT_FUNC0
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_OTHER2 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_12 {40, 0}  /* E0UC[28] / eMIOS_0 */
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_12_PORT_PIN_MODE_SPI0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_13 {41, 0}  /* E0UC[29] / eMIOS_0 */
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_13_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_14 {5, 0}  /* SCK_0 / DSPI_0 */
#define INPUT_SELECT_PORT_PIN_MODE_SPI0_PAD_14 {6, 0}  /* CS0_0 / DSPI_0 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_14 {38, 1}  /* E0UC[0] / eMIOS_0 */
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_SPI0 PORT_FUNC2
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_14_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_15 {5, 1}  /* SCK_0 / DSPI_0 */
#define INPUT_SELECT_PORT_PIN_MODE_SPI0_PAD_15 {6, 1}  /* CS0_0 / DSPI_0 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_15 {39, 1}  /* E0UC[1] / eMIOS_0 */
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_SPI0 PORT_FUNC1
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_15_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_16 {42, 0}  /* E0UC[30] / eMIOS_0 */
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_16_PORT_PIN_MODE_LIN PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_17 {43, 0}  /* E0UC[31] / eMIOS0 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_17 {62, 1}  /* LIN0RX/LINFlexD_0 */
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_17_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_18 {42, 1}  /* E0UC[30] / eMIOS_0 */
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_18_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_19 {43, 1}  /* E0UC[31] / eMIOS0 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_19 {62, 0}  /* LIN0RX/LINFlexD_0 */
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define PIN_FUNCTION_REG_19_PORT_PIN_MODE_LIN PORT_FUNC0
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_OTHER1 PORT_GPIO_APC
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_OTHER1 PORT_GPIO_APC
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_OTHER1 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_27 {6, 2}  /* CS0_0 / DSPI_0 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_27 {13, 1}  /* E1UC[3] / eMIOS_0 */
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_28 {14, 1}  /* E0UC[4] / eMIOS_0 */
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_29 {15, 1}  /* E0UC[5] / eMIOS_0 */
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_30 {16, 1}  /* E0UC[6] / eMIOS_0 */
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_31 {17, 1}  /* E0UC[7] / eMIOS_0 */
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_32_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_33_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_34 {7, 0}  /* SCK_1 / DSPI_1 */
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_34_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_35 {0, 0}  /* CAN1RX / FlexCAN_1 */
#define INPUT_SELECT_PORT_PIN_MODE_CAN0_PAD_35 {3, 0}  /* CAN4RX / FlexCAN_4 */
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_ADC PORT_FUNC2
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_OTHER PORT_FUNC3
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_35_PORT_PIN_MODE_CAN0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_36 {2, 0}  /* CAN3RX / FlexCAN_3 */
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_36 {8, 0}  /* SIN_1 / DSPI_1 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_36 {57, 0}  /* E1UC[31] / eMIOS_1Reserved */
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_SPI PORT_FUNC0
#define PIN_FUNCTION_REG_36_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_OTHER PORT_FUNC3
#define PIN_FUNCTION_REG_37_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_38 {54, 0}  /* E1UC[28] / eMIOS_1 */
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_38_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_39 {55, 0}  /* E1UC[29] / eMIOS_1 */
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_LIN PORT_FUNC0
#define PIN_FUNCTION_REG_39_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_40 {13, 2}  /* E1UC[3] / eMIOS_0 */
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_40_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_41 {17, 2}  /* E0UC[7] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_41 {58, 0}  /* LIN2RX / LINFlex _2 */
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define PIN_FUNCTION_REG_41_PORT_PIN_MODE_LIN PORT_FUNC0
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_CAN0 PORT_FUNC2
#define PIN_FUNCTION_REG_42_PORT_PIN_MODE_ADC PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_43 {0, 1}  /* CAN1RX / FlexCAN_1 */
#define INPUT_SELECT_PORT_PIN_MODE_CAN0_PAD_43 {3, 1}  /* CAN4RX / FlexCAN_4 */
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_43_PORT_PIN_MODE_CAN0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_44 {11, 0}  /* SIN_2 / DSPI_2 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_44 {20, 0}  /* E0UC[12] / eMIOS_0 */
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_44_PORT_PIN_MODE_SPI PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_45 {21, 0}  /* E0UC[13] / eMIOS_0 */
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_45_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_46 {10, 0}  /* SCK_2 / DSPI_2 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_46 {22, 0}  /* E0UC[14] / eMIOS_0 */
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_46_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_47 {12, 0}  /* CS0_2 / DSPI_2 */
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_47_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_OTHER1 PORT_GPIO_APC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_OTHER PORT_FUNC0
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_OTHER1 PORT_GPIO_APC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_60 {25, 0}  /* E0UC[24] / eMIOS_0 */
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_61 {9, 1}  /* CS0_1 / DSPI_1 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_61 {26, 0}  /* E0UC[25] / eMIOS_0 */
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_62 {27, 0}  /* E0UC[26] / eMIOS_0 */
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_63 {28, 0}  /* E0UC[27] / eMIOS_0 */
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_64 {4, 0}  /* CAN5RX / FlexCAN_5 */
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_64_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_65_PORT_PIN_MODE_CAN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_66 {8, 1}  /* SIN_1 / DSPI_1 */
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_66_PORT_PIN_MODE_SPI PORT_FUNC0
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_67_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_68 {7, 1}  /* SCK_1 / DSPI_1 */
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_68_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_69 {9, 2}  /* CS0_1 / DSPI_1 */
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_69_PORT_PIN_MODE_ADC PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_70 {23, 0}  /* E0UC[22] / eMIOS_0 */
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_70_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_71 {24, 0}  /* E0UC[23] / eMIOS_0 */
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_71_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_72 {23, 1}  /* E0UC[22] / eMIOS_0 */
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_72_PORT_PIN_MODE_CAN0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_73 {1, 0}  /* CAN2RX / FlexCAN_2 */
#define INPUT_SELECT_PORT_PIN_MODE_CAN0_PAD_73 {2, 1}  /* CAN3RX / FlexCAN_3 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_73 {24, 1}  /* E0UC[23] / eMIOS_0 */
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_73_PORT_PIN_MODE_CAN0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_74 {56, 0}  /* E1UC[30] / eMIOS_1Reserved */
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_LIN PORT_FUNC1
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_OTHER PORT_FUNC3
#define PIN_FUNCTION_REG_74_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_75 {25, 2}  /* E0UC[24] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_75 {31, 1}  /* LIN3RX / LINFlex_3 */
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_LIN PORT_FUNC0
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_76 {11, 1}  /* SIN_2 / DSPI_2 */
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_SPI PORT_FUNC0
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_OTHER1 PORT_GPIO_APC
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_78 {10, 1}  /* SCK_2 / DSPI_2 */
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_79 {12, 1}  /* CS0_2 / DSPI_2 */
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_80 {18, 1}  /* E0UC[10] / eMIOS_0 */
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_81 {19, 1}  /* E0UC[11] / eMIOS_0 */
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_82 {12, 2}  /* CS0_2 / DSPI_2 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_82 {20, 1}  /* E0UC[12] / eMIOS_0 */
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_83 {21, 1}  /* E0UC[13] / eMIOS_0 */
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_84 {22, 1}  /* E0UC[14] / eMIOS_0 */
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_85 {23, 2}  /* E0UC[22] / eMIOS_0 */
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_86 {24, 2}  /* E0UC[23] / eMIOS_0 */
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_OTHER0 PORT_GPIO_APC
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_CAN0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_89 {1, 1}  /* CAN2RX / FlexCAN_2 */
#define INPUT_SELECT_PORT_PIN_MODE_CAN0_PAD_89 {2, 2}  /* CAN3RX / FlexCAN_3 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_89 {44, 1}  /* E1UC[1] / eMIOS_1 */
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_CAN0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_90 {45, 1}  /* E1UC[2] / eMIOS_1 */
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_LIN PORT_FUNC2
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_OTHER PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_91 {46, 1}  /* E1UC[3] / eMIOS_1 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_91 {59, 1}  /* LIN4RX / LINFlex _4Reserved */
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_92 {51, 0}  /* E1UC[25] / eMIOS_1 */
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_93 {52, 0}  /* E1UC[26] / eMIOS_1 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_93 {60, 1}  /* LIN5RX / LINFlex _5 */
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_94 {53, 0}  /* E1UC[27] / eMIOS_1 */
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_CAN0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_95 {0, 2}  /* CAN1RX / FlexCAN_1 */
#define INPUT_SELECT_PORT_PIN_MODE_CAN0_PAD_95 {3, 2}  /* CAN4RX / FlexCAN_4 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_95 {47, 1}  /* E1UC[4] / eMIOS_1 */
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_CAN0 PORT_FUNC0
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_97 {4, 1}  /* CAN5RX / FlexCAN_5 */
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_OTHER PORT_FUNC2
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_CAN PORT_FUNC0
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_99 {34, 0}  /* CS0_3 / DSPI_3 */
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_100 {32, 0}  /* SCK_3 / DSPI_3 */
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_101 {33, 0}  /* SIN_3 / DSPI_3 */
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_SPI PORT_FUNC0
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_103 {56, 1}  /* E1UC[30] / eMIOS_1Reserved */
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_OTHER0 PORT_FUNC2 /* Can be used for PWM and ICU */
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_104 {12, 3}  /* CS0_2 / DSPI_2 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_104 {49, 0}  /* E1UC[17] / eMIOS_1 */
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_LIN PORT_FUNC2
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_105 {10, 2}  /* SCK_2 / DSPI_2 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_105 {50, 0}  /* E1UC[18] / eMIOS_1 */
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_OTHER1 PORT_FUNC0
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_106 {25, 1}  /* E0UC[24] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_106 {36, 0}  /* SIN_4 / DSPI_4Reserved */
#define INPUT_SELECT_PORT_PIN_MODE_ICU0_PAD_106 {57, 1}  /* E1UC[31] / eMIOS_1Reserved */
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_ICU0 PORT_FUNC2
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_OTHER0 PORT_FUNC2 /* Can be used for PWM and ICU */
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_SPI PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_107 {26, 1}  /* E0UC[25] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_107 {37, 0}  /* CS0_4 / DSPI_4Reserved */
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_108 {27, 1}  /* E0UC[26] / eMIOS_0 */
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_109 {28, 1}  /* E0UC[27] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_109 {35, 0}  /* SCK_4 / DSPI_4 */
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_111 {44, 0}  /* E1UC[1] / eMIOS_1 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_111 {61, 0}  /* LIN8RX / LINFlex _8 */
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_111_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_112 {8, 2}  /* SIN_1 / DSPI_1 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_112 {45, 0}  /* E1UC[2] / eMIOS_1 */
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_112_PORT_PIN_MODE_SPI PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_113 {46, 0}  /* E1UC[3] / eMIOS_1 */
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_114 {7, 2}  /* SCK_1 / DSPI_1 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_114 {47, 0}  /* E1UC[4] / eMIOS_1 */
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_115 {9, 3}  /* CS0_1 / DSPI_1 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_115 {48, 0}  /* E1UC[5] / eMIOS_1 */
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_ADC PORT_FUNC3
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_OTHER1 PORT_FUNC2
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_OTHER PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_123 {37, 1}  /* CS0_4 / DSPI_4Reserved */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_123 {48, 1}  /* E1UC[5] / eMIOS_1 */
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_SPI0 PORT_FUNC2
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_OTHER PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_124 {32, 1}  /* SCK_3 / DSPI_3 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_124 {51, 1}  /* E1UC[25] / eMIOS_1 */
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_125 {34, 1}  /* CS0_3 / DSPI_3 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_125 {52, 1}  /* E1UC[26] / eMIOS_1 */
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_SPI0 PORT_FUNC2
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_OTHER PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_126 {35, 1}  /* SCK_4 / DSPI_4 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_126 {53, 1}  /* E1UC[27] / eMIOS_1 */
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_127 {49, 1}  /* E1UC[17] / eMIOS_1 */
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_PWM PORT_FUNC3
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_ICU PORT_FUNC3
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_OTHER PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_128 {40, 1}  /* E0UC[28] / eMIOS_0 */
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_129 {41, 1}  /* E0UC[29] / eMIOS_0 */
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_129 {61, 1}  /* LIN8RX / LINFlex _8 */
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_130 {42, 2}  /* E0UC[30] / eMIOS_0 */
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_LIN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_131 {43, 2}  /* E0UC[31] / eMIOS0 */
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_OTHER0 PORT_FUNC0
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_LIN PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_132 {54, 1}  /* E1UC[28] / eMIOS_1 */
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_133 {35, 2}  /* SCK_4 / DSPI_4 */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_133 {55, 1}  /* E1UC[29] / eMIOS_1 */
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_134 {37, 2}  /* CS0_4 / DSPI_4Reserved */
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_134 {56, 2}  /* E1UC[30] / eMIOS_1Reserved */
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_135 {57, 2}  /* E1UC[31] / eMIOS_1Reserved */
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_ICU PORT_FUNC1
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_139 {33, 1}  /* SIN_3 / DSPI_3 */
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_SPI PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_140 {34, 2}  /* CS0_3 / DSPI_3 */
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_142 {36, 1}  /* SIN_4 / DSPI_4Reserved */
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_SPI PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_143 {37, 3}  /* CS0_4 / DSPI_4Reserved */
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_SPI PORT_FUNC0
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_OTHER PORT_GPIO_APC
#define INPUT_SELECT_PORT_PIN_MODE_ICU_PAD_148 {50, 1}  /* E1UC[18] / eMIOS_1 */
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_OTHER PORT_FUNC1
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_PWM PORT_FUNC2
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_ICU PORT_FUNC2
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Added to be able to set ADC in logical way when not using yaml file to configure.
 * This is probably only relevant when not configuring with ArcticStudio 
 */
#define PIN_FUNCTION_REG_3_PORT_PIN_MODE_ADC PORT_GPIO_APC

#define PIN_FUNCTION_REG_7_PORT_PIN_MODE_ADC PORT_GPIO_APC

#define PIN_FUNCTION_REG_10_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_11_PORT_PIN_MODE_ADC PORT_GPIO_APC

#define PIN_FUNCTION_REG_20_PORT_PIN_MODE_ADC PORT_GPIO_APC 
#define PIN_FUNCTION_REG_21_PORT_PIN_MODE_ADC PORT_GPIO_APC 
#define PIN_FUNCTION_REG_22_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_23_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_24_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_25_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_26_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_27_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_28_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_29_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_30_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_31_PORT_PIN_MODE_ADC PORT_GPIO_APC

#define PIN_FUNCTION_REG_48_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_49_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_50_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_51_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_52_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_53_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_54_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_55_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_56_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_57_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_58_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_59_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_60_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_61_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_62_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_63_PORT_PIN_MODE_ADC PORT_GPIO_APC

#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_ADC PORT_GPIO_APC

#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_ADC PORT_GPIO_APC

#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_ADC PORT_GPIO_APC
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_ADC PORT_GPIO_APC

#endif  /* _SPC560B54PORTS_H */
