file_mappings = {
	'dio' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Dio.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Dio.arxml",
		"generators/mcal/mpc560x/Dio.expt" : "generators/mcal/mpc560x/Dio.expt",
		"generators/mcal/mpc560x/Dio.echk" : "generators/mcal/mpc560x/Dio.echk",
		"stylesheets/dio.yaml" : "stylesheets/dio.yaml",
		"arch/ppc/mpc55xx/drivers/Dio.c" : "arch/ppc/mpc55xx/drivers/Dio.c",
		"drivers/Dio/Dio.h" : "include/Dio.h"
	},
	'mcu' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Mcu.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Mcu.arxml",
		"generators/mcal/mpc560x/Mcu.expt" : "generators/mcal/mpc560x/Mcu.expt",
		"generators/mcal/mpc560x/Mcu.echk" : "generators/mcal/mpc560x/Mcu.echk",
		"stylesheets/mcu.yaml" : "stylesheets/mcu.yaml",
		"generators/utils/DemHelpers.eext" : "generators/utils/DemHelpers.eext",
		"arch/ppc/mpc55xx/drivers/Mcu_mpc5xxx.c" : "arch/ppc/mpc55xx/drivers/Mcu_mpc5xxx.c",
		"drivers/Mcu/Mcu.h" : "drivers/Mcu/Mcu.h",
		"drivers/Mcu/Mcu.c" : "drivers/Mcu/Mcu.c",
		"include/io.h" : "include/io.h",
		"include/Ramlog.h" : "include/Ramlog.h",
		"include/device_serial.h" : "include/device_serial.h",
		"include/xtoa.h" : "include/xtoa.h",
		"include/irq.h" : "include/irq.h",
		"include/bit.h" : "include/bit.h",
		"include/ppc/Cpu.h" : "include/ppc/Cpu.h",
		"include/Mcu_Arc.h" : "include/Mcu_Arc.h",
		"boards/generic/Mcu_Arc_Cfg.c" : "boards/generic/Mcu_Arc_Cfg.c",
		"boards/generic/Mcu_Arc_Cfg.h" : "boards/generic/Mcu_Arc_Cfg.h",
		"boards/generic/Mcu_Cfg.h" : "boards/generic/Mcu_Cfg.h",
		"arch/ppc/mpc55xx/integration/Mcu_Arc_mpc56xx.c" : "arch/ppc/mpc55xx/integration/Mcu_Arc_mpc56xx.c",
		"arch/ppc/mpc55xx/mm/mm.h" : "arch/ppc/mpc55xx/mm/mm.h",
	},
	'adc' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Adc.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Adc.arxml",
		"generators/mcal/mpc560x/Adc.expt" : "generators/mcal/mpc560x/Adc.expt",
		"generators/mcal/mpc560x/Adc.echk" : "generators/mcal/mpc560x/Adc.echk",
		"stylesheets/Adc.yaml" : "stylesheets/Adc.yaml",
		"arch/ppc/mpc55xx/drivers/Adc_560x.c" : "arch/ppc/mpc55xx/drivers/Adc_560x.c",
		"drivers/Adc/Adc.h" : "drivers/Adc/Adc.h",
		"drivers/Adc/Adc_Internal.c" : "drivers/Adc/Adc_Internal.c",
		"drivers/Adc/Adc_Internal.h" : "drivers/Adc/Adc_Internal.h",
	},
	'pwm' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Pwm.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Pwm.arxml",
		"generators/mcal/mpc560x/Pwm.expt" : "generators/mcal/mpc560x/Pwm.expt",
		"generators/mcal/mpc560x/Pwm.echk" : "generators/mcal/mpc560x/Pwm.echk",
		"stylesheets/pwm.yaml" : "stylesheets/pwm.yaml",
		"arch/ppc/mpc55xx/drivers/Pwm.c" : "arch/ppc/mpc55xx/drivers/Pwm.c",
		"drivers/Pwm/Pwm.h" : "include/Pwm.h",
		"common/cirq_buffer.c" : "common/cirq_buffer.c",
		"include/cirq_buffer.h" : "include/cirq_buffer.h",
	},
	'spi' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Spi.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Spi.arxml",
		"generators/mcal/mpc560x/Spi.expt" : "generators/mcal/mpc560x/Spi.expt",
		"generators/mcal/mpc560x/Spi.echk" : "generators/mcal/mpc560x/Spi.echk",
		"stylesheets/spi.yaml" : "stylesheets/spi.yaml",
		"arch/ppc/mpc55xx/drivers/Spi_dspi.c" : "arch/ppc/mpc55xx/drivers/Spi_dspi.c",
		"arch/ppc/mpc55xx/drivers/ip_dspi.h" : "arch/ppc/mpc55xx/drivers/ip_dspi.h",
		"drivers/Spi/Spi.c" : "drivers/Spi/Spi.c",
		"drivers/Spi/Spi_Internal.h" : "drivers/Spi/Spi_Internal.h",
		"include/Spi.h" : "include/Spi.h"
	},
	'gpt' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Gpt.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Gpt.arxml",
		"generators/mcal/mpc560x/Gpt.expt" : "generators/mcal/mpc560x/Gpt.expt",
		"generators/mcal/mpc560x/Gpt.echk" : "generators/mcal/mpc560x/Gpt.echk",
		"stylesheets/Gpt.yaml" : "stylesheets/Gpt.yaml",
		"arch/ppc/mpc55xx/drivers/Gpt.c" : "arch/ppc/mpc55xx/drivers/Gpt.c",
		"include/Gpt.h" : "include/Gpt.h",
		"include/Gpt_ConfigTypes.h" : "include/Gpt_ConfigTypes.h",
	},
	'eep' : {
		"drivers/Eep/Eep.c" : "drivers/Eep/Eep.c",
		"include/Eep.h" : "include/Eep.h",
		"include/Eep_ConfigTypes.h" : "include/Eep_ConfigTypes.h",
		"boards/mpc5607b_xpc560b/config/Eep_Cfg.h" : "boards/mpc5607b_xpc560b/config/Eep_Cfg.h",
		"boards/mpc5607b_xpc560b/config/Eep_Lcfg.c" : "boards/mpc5607b_xpc560b/config/Eep_Lcfg.c",
	},	
	'fls' : {
		"arch/ppc/mpc55xx/drivers/Fls.c" : "arch/ppc/mpc55xx/drivers/Fls.c",
		"drivers/Fls/Fls.h" : "include/Fls.h",
		"include/MemIf_Types.h" : "include/MemIf_Types.h",
		"drivers/Fls/Fls_ConfigTypes.h" : "include/Fls_ConfigTypes.h",
		"arch/ppc/mpc55xx/drivers/flash_ll_h7f_c90.c" : "arch/ppc/mpc55xx/drivers/flash_ll_h7f_c90.c",
		"arch/ppc/mpc55xx/drivers/flash_ll_h7f_c90.h" : "arch/ppc/mpc55xx/drivers/flash_ll_h7f_c90.h",
		"arch/ppc/mpc55xx/drivers/flash.h" : "arch/ppc/mpc55xx/drivers/flash.h",
		"arch/ppc/mpc55xx/drivers/flash_h7f_c90.c" : "arch/ppc/mpc55xx/drivers/flash_h7f_c90.c",
	},
	'wdg' : {
		"arch/ppc/mpc55xx/drivers/Wdg.c" : "arch/ppc/mpc55xx/drivers/Wdg.c",
		"drivers/Wdg/Wdg.h" : "include/Wdg.h",
		"include/WdgIf_Types.h" : "include/WdgIf_Types.h",
	},
	'port' : {
		"arxml/generic/ArcCore_EcucDefs_Generic_Port.arxml" : "arxml/generic/ArcCore_EcucDefs_Generic_Port.arxml",
		"arxml/mpc5xxx/PortPins_mpc5606b.yaml" : "arxml/mpc5xxx/PortPins_mpc5606b.yaml",
		"generators/generic/Port.expt" : "generators/generic/Port.expt",
		"generators/generic/Port.echk" : "generators/generic/Port.echk",
		"arch/ppc/mpc55xx/drivers/Port.c" : "arch/ppc/mpc55xx/drivers/Port.c",
		"include/Port.h" : "include/Port.h",
		"include/PortDefs.h" : "include/PortDefs.h",
		"arch/ppc/mpc55xx/drivers/mpc5606b_portdefs.h" : "arch/ppc/mpc55xx/drivers/mpc5606b_portdefs.h",
	},
	'can' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Can.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Can.arxml",
		"arxml/generic/ArcCore_EcucDefs_CanIf.arxml" : "arxml/generic/ArcCore_EcucDefs_CanIf.arxml",
		"generators/mcal/mpc560x/Can.expt" : "generators/mcal/mpc560x/Can.expt",
		"generators/mcal/mpc560x/Can.echk" : "generators/mcal/mpc560x/Can.echk",
		"stylesheets/can.yaml" : "stylesheets/can.yaml",
		"arch/ppc/mpc55xx/drivers/Can.c" : "arch/ppc/mpc55xx/drivers/Can.c",
		"drivers/Can/Can.h" : "drivers/Can/Can.h",
		"communication/CanIf/CanIf_Types.h" : "communication/CanIf/CanIf_Types.h", #Not standard
		"include/ComStack_Types.h" : "include/ComStack_Types.h",
		"drivers/Can/Can_GeneralTypes.h" : "drivers/Can/Can_GeneralTypes.h",
		"communication/CanIf/CanIf_Cbk.h" : "communication/CanIf/CanIf_Cbk.h",
		"include/isr.h" : "include/isr.h",
		"include/arc.h" : "include/arc.h",
	},
	'icu' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Icu.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Icu.arxml",
		"generators/mcal/mpc560x/Icu.expt" : "generators/mcal/mpc560x/Icu.expt",
		"generators/mcal/mpc560x/Icu.echk" : "generators/mcal/mpc560x/Icu.echk",
		"generators/utils/IcuHelpers560x.eext" : "generators/utils/IcuHelpers560x.eext",
		"stylesheets/icu.yaml" : "stylesheets/icu.yaml",
		"arch/ppc/mpc55xx/drivers/Icu.c" : "arch/ppc/mpc55xx/drivers/Icu.c",
		"include/Icu.h" : "include/Icu.h",
		"include/Icu_Internal.h" : "include/Icu_Internal.h",
	},
	'ocu' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_Ocu.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_Ocu.arxml",
		"generators/mcal/mpc560x/Ocu.expt" : "generators/mcal/mpc560x/Ocu.expt",
		"generators/mcal/mpc560x/Ocu.echk" : "generators/mcal/mpc560x/Ocu.echk",
		"stylesheets/ocu.yaml" : "stylesheets/ocu.yaml",
		"arch/ppc/mpc55xx/drivers/Ocu.c" : "arch/ppc/mpc55xx/drivers/Ocu.c",
		"arch/ppc/mpc55xx/drivers/Ocu_Irq.c" : "arch/ppc/mpc55xx/drivers/Ocu_Irq.c",
		"include/Ocu.h" : "include/Ocu.h",
		"include/Ocu_Internal.h" : "include/Ocu_Internal.h",
		"include/Ocu_MemMap.h" : "include/Ocu_MemMap.h",
	},
	'ramtst' : {
		"arxml/generic/ArcCore_EcucDefs_RamTst.arxml" : "arxml/generic/ArcCore_EcucDefs_RamTst.arxml",
		"generators/generic/RamTst.expt" : "generators/generic/RamTst.expt",
		"generators/generic/RamTst.echk" : "generators/generic/RamTst.echk",
		"stylesheets/ramtst.yaml" : "stylesheets/ramtst.yaml",
		"memory/RamTst/RamTst.c" : "memory/RamTst/RamTst.c",
		"include/RamTst.h" : "include/RamTst.h",
	},
	'lin' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_LinFlex.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_LinFlex.arxml",
		"generators/mcal/mpc560x/Lin.expt" : "generators/mcal/mpc560x/Lin.expt",
		"generators/mcal/mpc560x/Lin.echk" : "generators/mcal/mpc560x/Lin.echk",
		"generators/utils/LinHelpers.eext" : "generators/utils/LinHelpers.eext",
		"stylesheets/Lin.yaml" : "stylesheets/Lin.yaml",
		"arch/ppc/mpc55xx/drivers/LinFlex.c" : "arch/ppc/mpc55xx/drivers/LinFlex.c",
		"arch/ppc/mpc55xx/drivers/LinFlex_Common.c" : "arch/ppc/mpc55xx/drivers/LinFlex_Common.c",
		"arch/ppc/mpc55xx/drivers/LinFlex_Common.h" : "arch/ppc/mpc55xx/drivers/LinFlex_Common.h", 
		"include/Lin_ConfigTypes.h" : "include/Lin_ConfigTypes.h",
		"include/Lin_GeneralTypes.h" : "include/Lin_GeneralTypes.h",
		"include/Lin_Types.h" : "include/Lin_Types.h",
		"include/Lin.h" : "include/Lin.h",
	},		
	'kernel' : {
		"arch/ppc/mpc55xx/kernel/irq_mpc5xxx.h" : "arch/ppc/mpc55xx/kernel/irq_mpc5xxx.h",
		"arch/ppc/mpc55xx/kernel/irq_types.h" : "arch/ppc/mpc55xx/kernel/irq_types.h",
		"arch/ppc/crt0.sx" : "arch/ppc/crt0.sx",
	},
	'common' : {
		"arxml/autosar/ECUConfigurationParameters_412.arxml" : "arxml/autosar/ECUConfigurationParameters_412.arxml",
		"arxml/mpc5xxx/McalImplementations_mpc5606b.arxml" : "arxml/mpc5xxx/McalImplementations_mpc5606b.arxml",
		"generators/utils/CanHelpers.eext" : "generators/utils/CanHelpers.eext",
		"generators/utils/Helpers.eext" : "generators/utils/Helpers.eext",
		"generators/utils/GptHelpers.eext" : "generators/utils/GptHelpers.eext",
		"generators/utils/McuHelpers.eext" : "generators/utils/McuHelpers.eext",
		"generators/utils/PwmHelpers.eext" : "generators/utils/PwmHelpers.eext",
		"generators/utils/AdcHelpers.eext" : "generators/utils/AdcHelpers.eext",
        "generators/utils/AdcHelpersMpc560x.eext" : "generators/utils/AdcHelpersMpc560x.eext",
		"generators/utils/RamTstHelpers.eext" : "generators/utils/RamTstHelpers.eext",
		"generators/utils/LinHelpers.eext" : "generators/utils/LinHelpers.eext",
		"include/Std_Types.h" : "include/Std_Types.h",	
		"base/compiler/Compiler.h" : "base/compiler/Compiler.h",
		"include/Platform_Types.h" : "include/Platform_Types.h",		
		"include/Det.h" : "include/Det.h",
		"include/ppc/asm_ppc.h" : "include/ppc/asm_ppc.h",
		"include/debug.h" : "include/debug.h",
		"include/timer.h" : "include/timer.h",
		"include/ppc/mpc55xx.h" : "include/ppc/mpc55xx.h",
		"arch/ppc/mpc55xx/drivers/MPC5606B.h" : "arch/ppc/mpc55xx/drivers/MPC5606B.h",
		"arch/ppc/mpc55xx/drivers/ip_adc_mpc56xx.h" : "arch/ppc/mpc55xx/drivers/ip_adc_mpc56xx.h",
		"arch/ppc/mpc55xx/drivers/ip_edma.h" : "arch/ppc/mpc55xx/drivers/ip_edma.h",
		"arch/ppc/mpc55xx/drivers/ip_dspi.h" : "arch/ppc/mpc55xx/drivers/ip_dspi.h",
		"arch/ppc/mpc55xx/drivers/typedefs.h" : "arch/ppc/mpc55xx/drivers/typedefs.h",
		"arch/ppc/mpc55xx/drivers/ip_flexcan.h" : "arch/ppc/mpc55xx/drivers/ip_flexcan.h",
		"arch/ppc/mpc55xx/drivers/Cpu.c" : "arch/ppc/mpc55xx/drivers/Cpu.c",
		"arch/ppc/mpc55xx/mm/mm.c" : "arch/ppc/mpc55xx/mm/mm.c",
		"arch/ppc/mpc55xx/drivers/timer_tb.c" : "arch/ppc/mpc55xx/drivers/timer_tb.c",
		"integration/MemMap.h" : "integration/MemMap.h",
		"integration/Arc_MemMap.h" : "integration/Arc_MemMap.h",
		"include/sys/queue.h" : "include/sys/queue.h",
		"common/ramlog.c" : "common/ramlog.c",
		"common/xtoa.c" : "common/xtoa.c",
		"common/init.c" : "common/init.c",
		"arxml/McalDefinitions.yaml" : "arxml/McalDefinitions.yaml",
		"include/Arc_Types.h" : "include/Arc_Types.h",
	},
	'clib' : {
		"clib/clib_port.c" : "clib/clib_port.c",
		"clib/printf.c" : "clib/printf.c",
		"clib/assert.h" : "clib/assert.h",
		"clib/clib.h" : "clib/clib.h",
		"clib/stdio.h" : "clib/stdio.h",
	},
	'buildsystem' : {
		"makefile" : "makefile",
		"boards/board_common.mk" : "boards/board_common.mk",
		"scripts/cc_ghs.mk" : "scripts/cc_ghs.mk",
		"scripts/memory_footprint_ghs.awk" : "scripts/memory_footprint_ghs.awk",
		"scripts/project_defaults.mk" : "scripts/project_defaults.mk",
		"scripts/rules.mk" : "scripts/rules.mk",
		"scripts/version_check.mk" : "scripts/version_check.mk",
		"boards/mpc5607b_xpc560b/board_info.txt" : "boards/mpc5607b_xpc560b/board_info.txt",
		"boards/mpc5607b_xpc560b/build_config.mk" : "boards/mpc5607b_xpc560b/build_config.mk",
		"boards/mpc5607b_xpc560b/mpc5607b_xpc560b.yaml" : "boards/mpc5607b_xpc560b/mpc5607b_xpc560b.yaml",
		"boards/mpc5607b_xpc560b/config/Fls_Cfg.c" : "boards/mpc5607b_xpc560b/config/Fls_Cfg.c",
		"boards/mpc5607b_xpc560b/config/Fls_Cfg.h" : "boards/mpc5607b_xpc560b/config/Fls_Cfg.h",
		"boards/mpc5607b_xpc560b/config/Wdg_Cfg.h" : "boards/mpc5607b_xpc560b/config/Wdg_Cfg.h",
		"boards/mpc5607b_xpc560b/config/Wdg_Lcfg.c" : "boards/mpc5607b_xpc560b/config/Wdg_Lcfg.c",
		"arch/ppc/mpc55xx/scripts/linkscript_ghs.ldf" : "arch/ppc/mpc55xx/scripts/linkscript_ghs.ldf",
		"scripts/linker/memory_mcu.ldf" : "scripts/linker/memory_mcu.ldf",
		"scripts/linker/compiler.ldf" : "scripts/linker/compiler.ldf",
	},
	'integration' : {
		"include/Modules.h" : "include/Modules.h",
	},
	'project_files' : {
		".project" : ".project",
		".cproject" : ".cproject",
		".settings/com.arccore.prefs" : ".settings/com.arccore.prefs",
		".settings/org.eclipse.core.resources.prefs" : ".settings/org.eclipse.core.resources.prefs",

	}
}

patch_file_mappings = {
	'patch' : {
		"build_config.mk" : "boards/mpc5607b_xpc560b/build_config.mk",
	},
}