file_mappings = {
	'icu' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Icu.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Icu.arxml",
		"generators/mcal/mpc560x/Icu.echk" : "generators/mcal/mpc560x/Icu.chk",
		"generators/mcal/mpc560x/Icu.expt" : "generators/mcal/mpc560x/Icu.xpt",
		"generators/utils/IcuHelpers560x.eext" : "generators/utils/IcuHelpers560x.ext",
		"stylesheets/icu.yaml" : "stylesheets/icu.yaml",
		"arch/ppc/mpc55xx/drivers/Icu.c" : "arch/ppc/mpc55xx/drivers/Icu.c",
		"include/Icu.h" : "include/Icu.h",
	},
	'ocu' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_Ocu.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_Ocu.arxml",
		"generators/mcal/mpc560x/Ocu.echk" : "generators/mcal/mpc560x/Ocu.chk",
		"generators/mcal/mpc560x/Ocu.expt" : "generators/mcal/mpc560x/Ocu.xpt",
		"include/Ocu.h" : "include/Ocu.h",
		"arch/ppc/mpc55xx/drivers/Ocu.c" : "arch/ppc/mpc55xx/drivers/Ocu.c",
		"arch/ppc/mpc55xx/drivers/Ocu_Irq.c" : "arch/ppc/mpc55xx/drivers/Ocu_Irq.c",
		"include/Ocu_MemMap.h" : "include/Ocu_MemMap.h",
		"include/Ocu_Internal.h" : "include/Ocu_Internal.h",
		"stylesheets/ocu.yaml" : "stylesheets/ocu.yaml",
	},
	'lin' : {
		"arch/ppc/mpc55xx/drivers/LinFlex.c" : "arch/ppc/mpc55xx/drivers/LinFlex.c",
		"arxml/mpc5xxx/ArcCore_EcucDefs_LinFlex.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_LinFlex.arxml",
		"generators/mcal/mpc560x/Lin.echk" : "generators/mcal/mpc560x/Lin.chk",
		"generators/mcal/mpc560x/Lin.expt" : "generators/mcal/mpc560x/Lin.xpt",
		"generators/utils/LinHelpers.eext" : "generators/utils/LinHelpers.ext",
		"include/Lin_ConfigTypes.h" : "include/Lin_ConfigTypes.h",
		"include/Lin_Types.h" : "include/Lin_Types.h",
		"include/Lin.h" : "include/Lin.h",
		"stylesheets/Lin.yaml" : "stylesheets/Lin.yaml",
	},
	'ramtst' : {
		"arxml/generic/ArcCore_EcucDefs_RamTst.arxml" : "arxml/generic/ArcCore_EcucDefs_RamTst.arxml",
		"generators/generic/RamTst.echk" : "generators/generic/RamTst.chk",
		"generators/generic/RamTst.expt" : "generators/generic/RamTst.xpt",
		"generators/utils/RamTstHelpers.eext" : "generators/utils/RamTstHelpers.ext",
		"include/RamTst.h" : "include/RamTst.h",
		"memory/RamTst/RamTst.c" : "memory/RamTst/RamTst.c",
		"stylesheets/ramtst.yaml" : "stylesheets/ramtst.yaml",
	},
	'dio' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Dio.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Dio.arxml",
		"generators/mcal/mpc560x/Dio.xpt" : "generators/mcal/mpc560x/Dio.xpt",
		"generators/mcal/mpc560x/Dio.chk" : "generators/mcal/mpc560x/Dio.chk",
		"stylesheets/dio.yaml" : "stylesheets/dio.yaml",
		"arch/ppc/mpc55xx/drivers/Dio.c" : "arch/ppc/mpc55xx/drivers/Dio.c",
		"drivers/Dio/Dio.h" : "include/Dio.h"
	},
	'mcu' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Mcu.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Mcu.arxml",
		"generators/mcal/mpc560x/Mcu.xpt" : "generators/mcal/mpc560x/Mcu.xpt",
		"generators/mcal/mpc560x/Mcu.chk" : "generators/mcal/mpc560x/Mcu.chk",
		"stylesheets/mcu.yaml" : "stylesheets/mcu.yaml",
		"generators/utils/DemHelpers.ext" : "generators/utils/DemHelpers.ext",
		"arch/ppc/mpc55xx/drivers/Mcu_mpc5xxx.c" : "arch/ppc/mpc55xx/drivers/Mcu_mpc5xxx.c",
		"drivers/Mcu/Mcu.h" : "drivers/Mcu/Mcu.h",
		"drivers/Mcu/Mcu.c" : "drivers/Mcu/Mcu.c",
		"include/io.h" : "include/io.h",
		"include/Ramlog.h" : "include/Ramlog.h",
		"include/device_serial.h" : "include/device_serial.h",
		"include/xtoa.h" : "include/xtoa.h",
		"include/irq.h" : "include/irq.h",
		"include/bit.h" : "include/bit.h",
		"include/Mcu_Arc.h" : "include/Mcu_Arc.h",
		"boards/generic/Mcu_Arc_Cfg.c" : "boards/generic/Mcu_Arc_Cfg.c",
		"boards/generic/Mcu_Arc_Cfg.h" : "boards/generic/Mcu_Arc_Cfg.h",
		"arch/ppc/mpc55xx/integration/Mcu_Arc_mpc56xx.c" : "arch/ppc/mpc55xx/integration/Mcu_Arc_mpc56xx.c",
		"arch/ppc/mpc55xx/mm/mm.h" : "arch/ppc/mpc55xx/mm/mm.h",
	},
	'adc' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Adc.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Adc.arxml",
		"generators/mcal/mpc560x/Adc.xpt" : "generators/mcal/mpc560x/Adc.xpt",
		"generators/mcal/mpc560x/Adc.chk" : "generators/mcal/mpc560x/Adc.chk",
		"stylesheets/adc.yaml" : "stylesheets/adc.yaml",
		"arch/ppc/mpc55xx/drivers/Adc_560x.c" : "arch/ppc/mpc55xx/drivers/Adc_560x.c",
		"include/Adc.h" : "include/Adc.h",
		"drivers/Adc/Adc_Internal.c" : "drivers/Adc/Adc_Internal.c",
		"drivers/Adc/Adc_Internal.h" : "drivers/Adc/Adc_Internal.h",
	},
	'pwm' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Pwm.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Pwm.arxml",
		"generators/mcal/mpc560x/Pwm.xpt" : "generators/mcal/mpc560x/Pwm.xpt",
		"generators/mcal/mpc560x/Pwm.chk" : "generators/mcal/mpc560x/Pwm.chk",
		"stylesheets/pwm.yaml" : "stylesheets/pwm.yaml",
		"arch/ppc/mpc55xx/drivers/Pwm.c" : "arch/ppc/mpc55xx/drivers/Pwm.c",
		"drivers/Pwm/Pwm.h" : "include/Pwm.h",
		"common/cirq_buffer.c" : "common/cirq_buffer.c",
		"include/cirq_buffer.h" : "include/cirq_buffer.h",
	},
	'spi' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Spi.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Spi.arxml",
		"generators/mcal/mpc560x/Spi.xpt" : "generators/mcal/mpc560x/Spi.xpt",
		"generators/mcal/mpc560x/Spi.chk" : "generators/mcal/mpc560x/Spi.chk",
		"stylesheets/spi.yaml" : "stylesheets/spi.yaml",
		"arch/ppc/mpc55xx/drivers/Spi.c" : "arch/ppc/mpc55xx/drivers/Spi.c",
		"include/Spi.h" : "include/Spi.h"
	},
	'gpt' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Gpt.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Gpt.arxml",
		"generators/mcal/mpc560x/Gpt.xpt" : "generators/mcal/mpc560x/Gpt.xpt",
		"generators/mcal/mpc560x/Gpt.chk" : "generators/mcal/mpc560x/Gpt.chk",
		"stylesheets/gpt.yaml" : "stylesheets/gpt.yaml",
		"arch/ppc/mpc55xx/drivers/Gpt.c" : "arch/ppc/mpc55xx/drivers/Gpt.c",
		"include/Gpt.h" : "include/Gpt.h",
		"include/Gpt_ConfigTypes.h" : "include/Gpt_ConfigTypes.h",
	},
	'fls' : {
		"arch/ppc/mpc55xx/drivers/Fls.c" : "arch/ppc/mpc55xx/drivers/Fls.c",
		"drivers/Fls/Fls.h" : "include/Fls.h",
		"include/MemIf_Types.h" : "include/MemIf_Types.h",
		"drivers/Fls/Fls_ConfigTypes.h" : "include/Fls_ConfigTypes.h",
		"arch/ppc/mpc55xx/drivers/flash_ll_h7f_c90.c" : "arch/ppc/mpc55xx/drivers/flash_ll_h7f_c90.c",
		"arch/ppc/mpc55xx/drivers/flash_ll_h7f_c90.h" : "arch/ppc/mpc55xx/drivers/flash_ll_h7f_c90.h",
		"arch/ppc/mpc55xx/drivers/flash.h" : "arch/ppc/mpc55xx/drivers/flash.h",
		"arch/ppc/mpc55xx/drivers/flash_h7f_c90.c" : "arch/ppc/mpc55xx/drivers/flash_h7f_c90.c",
	},
	'wdg' : {
		"arch/ppc/mpc55xx/drivers/Wdg.c" : "arch/ppc/mpc55xx/drivers/Wdg.c",
		"drivers/Wdg/Wdg.h" : "include/Wdg.h",
		"include/WdgIf_Types.h" : "include/WdgIf_Types.h",
	},
	'port' : {
		"arxml/generic/ArcCore_EcucDefs_Generic_Port.arxml" : "arxml/generic/ArcCore_EcucDefs_Generic_Port.arxml",
		"arxml/mpc5xxx/PortPins_MPC5645S.yaml" : "arxml/mpc5xxx/PortPins_MPC5645S.yaml",
		"generators/generic/Port.xpt" : "generators/generic/Port.xpt",
		"generators/generic/Port.chk" : "generators/generic/Port.chk",
		"arch/ppc/mpc55xx/drivers/Port.c" : "arch/ppc/mpc55xx/drivers/Port.c",
		"include/Port.h" : "include/Port.h",
		"include/PortDefs.h" : "include/PortDefs.h",
		"arch/ppc/mpc55xx/drivers/MPC5645S_portdefs.h" : "arch/ppc/mpc55xx/drivers/MPC5645S_portdefs.h",
	},
	'can' : {
		"arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Can.arxml" : "arxml/mpc5xxx/ArcCore_EcucDefs_mpc560x_Can.arxml",
		"arxml/generic/ArcCore_EcucDefs_CanIf.arxml" : "arxml/generic/ArcCore_EcucDefs_CanIf.arxml",
		"generators/mcal/mpc560x/Can.xpt" : "generators/mcal/mpc560x/Can.xpt",
		"generators/mcal/mpc560x/Can.chk" : "generators/mcal/mpc560x/Can.chk",
		"stylesheets/can.yaml" : "stylesheets/can.yaml",
		"arch/ppc/mpc55xx/drivers/Can.c" : "arch/ppc/mpc55xx/drivers/Can.c",
		"include/Can.h" : "include/Can.h",
		"include/CanIf_Types.h" : "include/CanIf_Types.h", #Not standard
		"include/ComStack_Types.h" : "include/ComStack_Types.h",
		"include/Can_GeneralTypes.h" : "include/Can_GeneralTypes.h",
		"include/CanIf_Cbk.h" : "include/CanIf_Cbk.h",
		"include/isr.h" : "include/isr.h",
		"include/arc.h" : "include/arc.h",
	},
	'os' : {
		"system/Os/makefile" : "system/Os/makefile",
	},
	'kernel' : {
		"arch/ppc/mpc55xx/kernel/irq_mpc5645s.h" : "arch/ppc/mpc55xx/kernel/irq_mpc5645s.h",
		"arch/ppc/mpc55xx/kernel/irq_mpc5xxx.h" : "arch/ppc/mpc55xx/kernel/irq_mpc5xxx.h",
		"arch/ppc/mpc55xx/kernel/irq_types.h" : "arch/ppc/mpc55xx/kernel/irq_types.h",
		"arch/ppc/crt0.sx" : "arch/ppc/crt0.sx",
	},
	'common' : {
		"arxml/autosar/ECUConfigurationParameters_412.arxml" : "arxml/autosar/ECUConfigurationParameters_412.arxml",
		"arxml/mpc5xxx/McalImplementations_mpc5645s.arxml" : "arxml/mpc5xxx/McalImplementations_mpc5645s.arxml",
		"generators/utils/CanHelpers.ext" : "generators/utils/CanHelpers.ext",
		"generators/utils/Helpers.ext" : "generators/utils/Helpers.ext",
		"generators/utils/GptHelpers.ext" : "generators/utils/GptHelpers.ext",
		"generators/utils/McuHelpers.ext" : "generators/utils/McuHelpers.ext",
		"generators/utils/PwmHelpers.ext" : "generators/utils/PwmHelpers.ext",
		"generators/utils/AdcHelpers.ext" : "generators/utils/AdcHelpers.ext",
        "generators/utils/AdcHelpersMpc560x.eext" : "generators/utils/AdcHelpersMpc560x.eext",
		"include/Std_Types.h" : "include/Std_Types.h",	
		"base/compiler/Compiler.h" : "base/compiler/Compiler.h",
		"include/Platform_Types.h" : "include/Platform_Types.h",		
		"include/Det.h" : "include/Det.h",
		"include/ppc/asm_ppc.h" : "include/ppc/asm_ppc.h",
		"include/debug.h" : "include/debug.h",
		"include/timer.h" : "include/timer.h",
		"include/ppc/mpc55xx.h" : "include/ppc/mpc55xx.h",
		"arch/ppc/mpc55xx/drivers/MPC5645S.h" : "arch/ppc/mpc55xx/drivers/MPC5645S.h",
		"arch/ppc/mpc55xx/drivers/typedefs.h" : "arch/ppc/mpc55xx/drivers/typedefs.h",
		"arch/ppc/mpc55xx/drivers/ip_flexcan.h" : "arch/ppc/mpc55xx/drivers/ip_flexcan.h",
		"arch/ppc/mpc55xx/drivers/Cpu.c" : "arch/ppc/mpc55xx/drivers/Cpu.c",
		"arch/ppc/mpc55xx/mm/mm.c" : "arch/ppc/mpc55xx/mm/mm.c",
		"arch/ppc/mpc55xx/drivers/timer_tb.c" : "arch/ppc/mpc55xx/drivers/timer_tb.c",
		"integration/MemMap.h" : "integration/MemMap.h",
		"integration/Arc_MemMap.h" : "integration/Arc_MemMap.h",
		"include/sys/queue.h" : "include/sys/queue.h",
		"common/init.c" : "common/init.c",
		"arxml/McalDefinitions.yaml" : "arxml/McalDefinitions.yaml",
		"include/Arc_Types.h" : "include/Arc_Types.h",
	},
	'clib' : {
		"clib/assert.h" : "clib/assert.h",
		"clib/clib.h" : "clib/clib.h",
		"clib/stdio.h" : "clib/stdio.h",
	},
	'buildsystem' : {
		"makefile" : "makefile",
		"boards/board_common.mk" : "boards/board_common.mk",
		"scripts/cc_ghs.mk" : "scripts/cc_ghs.mk",
		"scripts/memory_footprint_ghs.awk" : "scripts/memory_footprint_ghs.awk",
		"scripts/project_defaults.mk" : "scripts/project_defaults.mk",
		"scripts/rules.mk" : "scripts/rules.mk",
		"scripts/version_check.mk" : "scripts/version_check.mk",
		"boards/mpc5645s_demo_v2/board_info.txt" : "boards/mpc5645s_demo_v2/board_info.txt",
		"boards/mpc5645s_demo_v2/build_config.mk" : "boards/mpc5645s_demo_v2/build_config.mk",
		"boards/mpc5645s_demo_v2/mpc5645s_demo_v2l.yaml" : "boards/mpc5645s_demo_v2/mpc5645s_demo_v2l.yaml",
		"boards/mpc5645s_demo_v2/config/Fls_Cfg.c" : "boards/mpc5645s_demo_v2/config/Fls_Cfg.c",
		"boards/mpc5645s_demo_v2/config/Fls_Cfg.h" : "boards/mpc5645s_demo_v2/config/Fls_Cfg.h",
		"boards/mpc5645s_demo_v2/config/Wdg_Cfg.h" : "boards/mpc5645s_demo_v2/config/Wdg_Cfg.h",
		"boards/mpc5645s_demo_v2/config/Wdg_Lcfg.c" : "boards/mpc5645s_demo_v2/config/Wdg_Lcfg.c",
		"arch/ppc/mpc55xx/scripts/linkscript_ghs.ldf" : "arch/ppc/mpc55xx/scripts/linkscript_ghs.ldf",
		"scripts/linker/memory_mcu.ldf" : "scripts/linker/memory_mcu.ldf",
		"scripts/linker/compiler.ldf" : "scripts/linker/compiler.ldf",
	},
	'integration' : {
		# "include/Modules.h" : "include/Modules.h",
	},
	'project_files' : {
		".project" : ".project",
		".cproject" : ".cproject",
		".settings/com.arccore.prefs" : ".settings/com.arccore.prefs",
		".settings/org.eclipse.core.resources.prefs" : ".settings/org.eclipse.core.resources.prefs",

	}
}

patch_file_mappings = {
	'patch' : {
		"mpc5645s_build_config.mk" : "boards/mpc5645s_demo_v2/build_config.mk",
		"Fls_Cfg.h" : "boards/mpc5645s_demo_v2/config/Fls_Cfg.h",
	},
}